apiVersion: v1
kind: Service
metadata:
  name: "lgd-backend-welcome"
  labels:
    {{- include "lgd-backend-welcome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lgd-backend-welcome.selectorLabels" . | nindent 4 }}
