apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.userCredential.secretName }}-static
  namespace: {{ include "promstackNamespace" . }}
type: Opaque
data:
  grafana_user: {{ .Values.userCredential.user | b64enc | quote }}
  grafana_password: {{ .Values.userCredential.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminCredential.secretName }}-static
  namespace: {{ include "promstackNamespace" . }}
type: Opaque
data:
  admin_user: {{ .Values.adminCredential.user | b64enc | quote }}
  admin_password: {{ .Values.adminCredential.password | b64enc | quote }}
