apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-service-client-job
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 10  # Job이 완료된 후 100초 뒤에 자동으로 삭제됩니다
  template:
    metadata:
      name: create-kibana-client-pod
      namespace: {{ .Release.Namespace }}
    spec:
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        {{- toYaml .Values.tolerations.values | nindent 8 }}
      {{- end }}
      serviceAccountName: keycloak-kibana-sa
      containers:
      - name: create-kibana-client
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        image: "{{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python"]
        args: ["create_kibana_client.py"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"        
        - name: KIBANA_NAMESPACE
          value: "{{ .Values.kibana.namespace }}"
        - name: KIBANA_KEYCLOAK_CLIENT
          value: "{{ .Values.kibana.keycloakClient }}"
        - name: KIBANA_GRANT_TYPE
          value: "{{ .Values.kibana.grantType }}"
        - name: KEYCLOAK_NAMESPACE
          value: "{{ .Values.keycloak.namespace }}"
        - name: KEYCLOAK_SECRET_NAME
          value: "{{ .Values.keycloak.secretName }}"
        - name: KEYCLOAK_SERVICE_CLIENT_SECRET_NAME
          value: "{{ .Values.keycloak.serviceClientSecretName }}"
        - name: KEYCLOAK_SERVICE_CLIENT_NAME
          value: "{{ .Values.keycloak.serviceClientName }}"
        - name: KEYCLOAK_URL
          value: "{{ .Values.keycloak.url }}"
        - name: KEYCLOAK_TLS_VERIFY
          value: "{{ .Values.keycloak.tlsVerify}}"          
        - name: ADMIN_CLIENT_ID
          value: "{{ .Values.keycloak.adminClientId }}"
        - name: ADMIN_USERNAME
          value: "{{ .Values.keycloak.adminUsername }}"
        - name: TARGET_REALMS
          value: "{{ .Values.targetRealms }}"
        - name: K8S_CONFIG_PATH
          value: "{{ .Values.k8sConfigPath }}"
      restartPolicy: OnFailure
  backoffLimit: 4
