---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-grafana-secret-manager
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-secret-reader
  namespace: {{ .Values.keycloak.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-grafana-secret-reader-binding
  namespace: {{ .Values.keycloak.namespace }}
subjects:
- kind: ServiceAccount
  name: keycloak-grafana-secret-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: keycloak-secret-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-secret-writer
  namespace: {{ .Values.grafana.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-secret-writer-binding
  namespace: {{ .Values.grafana.namespace }}
subjects:
- kind: ServiceAccount
  name: keycloak-grafana-secret-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: grafana-secret-writer
  apiGroup: rbac.authorization.k8s.io