# Default values for aipub-crd-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: "aipub-crd-exporter"
  # This sets the pull policy for images.
  pullPolicy: "Never"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 31019
  targetPort: 8000

# Monitoring settings for Prometheus
monitoring:
  # The release name of the kube-prometheus-stack.
  prometheusRelease: "kube-prometheus-stack"
  # How frequently to scrape metrics from the exporter.
  interval: "30s"
  # The timeout for scraping metrics.
  timeout: "10s"

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"

nodeSelector: {}

# Node affinity for pod scheduling.
# ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

# Tolerations for pod scheduling.
# ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

clusterRole:
  rules:
    - apiGroups: ["aipub.ten1010.io"]   # 감시할 CRD의 apiGroup
      resources: ["workspaces", "aipubjobs"]  # 감시할 CRD의 plural 이름
      verbs: ["get", "list", "watch"]
