- hosts: k8s_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Execute 1_cert.sh
      shell: "sudo {{ ki_env_scripts_path }}/ki-cp-node/services/java/{{ java_service_version }}/1_cert.sh --config {{ java_service_config_path }}"
      when: inventory_hostname == k8s_cp_nodes | first
