{
 "title": "Ten Workspace Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(aipub_workspace_info{job=\"aipub-crd-exporter\"}, workspace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workspace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (label_workspaces_aipub_ten1010_io_owner) (\n  kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n)",
     "legendFormat": "{{workspace}}"
    }
   ]
  },
  {
   "title": "Project",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipub_workspace_info{project=\"$namespace\", workspace=\"$workspace\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipub_workspace_ready_condition{project=\"$namespace\", workspace=\"$workspace\"}"
    }
   ]
  },
  {
   "title": "Suspend",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipub_workspace_spec_suspend{project=\"$namespace\", workspace=\"$workspace\"}"
    }
   ]
  },
  {
   "title": "Pod Conditions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  kube_pod_labels{label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n  * on (namespace, pod, uid) group_left(phase, condition)\n  (kube_pod_status_phase{phase=\"Pending\"} == 1)\n) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum (\n  kube_pod_labels{label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n  * on (namespace, pod, uid) group_left(phase, condition)\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on (namespace, pod, uid) group_left(condition)\n  (kube_pod_status_ready{condition=\"false\"} == 1)\n) or vector(0)",
     "legendFormat": "Progressing"
    },
    {
     "expr": "sum (\n  kube_pod_labels{label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n  * on (namespace, pod, uid) group_left(phase, condition)\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n  * on (namespace, pod, uid) group_left(condition)\n  (kube_pod_status_ready{condition=\"true\"} == 1)\n) or vector(0)",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - aipub_workspace_created{project=\"$namespace\", workspace=\"$workspace\"}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}\n* on (namespace, pod, uid) group_left(label_workspaces_aipub_ten1010_io_owner)\nkube_pod_labels{label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n* on (namespace, pod, uid) group_left(condition)\n(kube_pod_status_ready{namespace=\"$namespace\"} == 1)\n* on (namespace, pod, uid) group_left(reason)\n(\n  kube_pod_container_status_running{\n    namespace=\"$namespace\", container=~\"$workspace.*\"\n  } == 1\n  or\n  on (namespace, pod, uid) kube_pod_container_status_waiting_reason{\n    namespace=\"$namespace\", container=~\"$workspace.*\"\n  } == 1\n  or\n  on (namespace, pod, uid) kube_pod_container_status_waiting_reason{\n    namespace=\"$namespace\", container=~\"$workspace.*\"\n  } == 1\n)"
    }
   ]
  },
  {
   "title": "Workspace 할당 GPU / MIG 인스턴스",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum by (Hostname, gpu, UUID, modelName, exported_namespace, exported_pod) (\n  label_replace(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", UUID=~\"GPU.*\"}\n    * on (exported_namespace, exported_pod) group_left()\n    label_replace(\n      label_replace(\n        kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n        * on (namespace, pod) group_left()\n        (kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} == 1)\n        , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n    )\n    , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n  )\n)\n* on (Hostname, gpu, UUID, GPU_I_ID) group_left(device, modelName)\nsgn(gpu:resource:gpu_temp)\nor\nsum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod) (\n  MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n  * on (exported_namespace, exported_pod) group_left()\n  label_replace(\n    label_replace(\n      kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n      * on (namespace, pod) group_left()\n      (kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} == 1)\n      , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n  )\n)\n* on(Hostname, gpu, UUID, GPU_I_ID) group_left(device, modelName, GPU_I_PROFILE)\nsgn(gpu:resource:gpu_temp)"
    }
   ]
  },
  { "title": "시스템", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", image!=\"\"}[5m])\n  * on (namespace, pod) group_left()\n  kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace, pod) group_left(label_workspaces_aipub_ten1010_io_owner)\r\r\n  kube_pod_labels{namespace=~\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n)\r\n\r",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "gpu:resource:gpu_temp\n* on (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE) group_right(modelName)\nsgn(\n  sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, exported_namespace, exported_pod) (\n    label_replace(\n      GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n      , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n    )\n  )\n)\nor\ngpu:resource:gpu_temp\n* on (Hostname, gpu, UUID, GPU_I_ID) group_right(modelName, GPU_I_PROFILE)\nsgn(\n  sum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod) (\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n    * on (exported_namespace, exported_pod) group_left()\n    label_replace(\n      label_replace(\n        kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n        , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "description": "GPU  전력 소모량",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:power\n  * on (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE) group_right(modelName)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, exported_namespace, exported_pod, exported_container) (\n      label_replace(\n        GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\"}\n        * on (exported_namespace, exported_pod) group_left()\n        label_replace(\n          label_replace(\n            kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n            , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n          ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n        )\n        , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n      )\n    )\n  )\n)\nor\nsum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:power\n  * on (Hostname, gpu, UUID, GPU_I_ID) group_right(modelName, GPU_I_PROFILE)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod, exported_container) (\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:util\n  * on (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE) group_right(modelName)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, exported_namespace, exported_pod, exported_container) (\n      label_replace(\n        GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\"}\n        * on (exported_namespace, exported_pod) group_left()\n        label_replace(\n          label_replace(\n            kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n            , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n          ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n        )\n        , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n      )\n    )\n  )\n)\nor\nsum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:util\n  * on (Hostname, gpu, UUID, GPU_I_ID) group_right(modelName, GPU_I_PROFILE)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod, exported_container) (\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "연산 자원의 공간 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:sm_active\n  * on (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE) group_right(modelName)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, exported_namespace, exported_pod, exported_container) (\n      label_replace(\n        GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\"}\n        * on (exported_namespace, exported_pod) group_left()\n        label_replace(\n          label_replace(\n            kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n            , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n          ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n        )\n        , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n      )\n    )\n  )\n)\nor\nsum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:sm_active\n  * on (Hostname, gpu, UUID, GPU_I_ID) group_right(modelName, GPU_I_PROFILE)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod, exported_container) (\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "description": "GPU의 연산자원 중 텐서코어의 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:tensor_core\n  * on (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE) group_right(modelName)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, exported_namespace, exported_pod, exported_container) (\n      label_replace(\n        GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\"}\n        * on (exported_namespace, exported_pod) group_left()\n        label_replace(\n          label_replace(\n            kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n            , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n          ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n        )\n        , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n      )\n    )\n  )\n)\nor\nsum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:tensor_core\n  * on (Hostname, gpu, UUID, GPU_I_ID) group_right(modelName, GPU_I_PROFILE)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod, exported_container) (\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "GPU Memory R/W Utilization",
   "type": "graph",
   "description": "GPU 메모리의 읽고 쓰기 시간을 합한 시간의 비율 \n(GPU Memory bandwidth)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:dram_active\n  * on (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE) group_right(modelName)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, exported_namespace, exported_pod, exported_container) (\n      label_replace(\n        GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\"}\n        * on (exported_namespace, exported_pod) group_left()\n        label_replace(\n          label_replace(\n            kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n            * on (namespace, pod) group_left()\n            (kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} == 1)\n            , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n          ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n        )\n        , \"Hostname\", \"$1\", \"node\", \"(.*)\"\n      )\n    )\n  )\n)\nor\nsum by (Hostname, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  gpu:resource:dram_active\n  * on (Hostname, gpu, UUID, GPU_I_ID) group_right(modelName, GPU_I_PROFILE)\n  sgn(\n    sum by (Hostname, gpu, UUID, GPU_I_ID, MIG_UUID, exported_namespace, exported_pod, exported_container) (\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          * on (namespace, pod) group_left()\n          (kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"} == 1)\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU 메모리 활용 크기",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  GPU_POD_MEMORY{exported_namespace=\"$namespace\", exported_pod=~\"$workspace.*\"}\n  * on(exported_namespace, exported_pod, UUID) group_left(gpu, GPU_I_ID, GPU_I_PROFILE, exported_container)\n  sgn(\n    label_replace(\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$workspace.*\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      ), \"UUID\", \"$1\", \"MIG_UUID\", \"(.*)\"\n    )\n    or\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod!=\"$workspace.*\", UUID=~\"GPU.*\"}\n    * on (exported_namespace, exported_pod) group_left()\n    label_replace(\n      label_replace(\n        kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n        , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} {{modelName}}({{gpu}}) {{GPU_I_PROFILE}} {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "Network Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  irate(container_network_receive_bytes_total{namespace=\"$namespace\", image!=\"\"}[$__rate_interval])\n  * on (namespace, pod) group_left()\n  kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\n  irate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])\n  * on (namespace, pod) group_left()\n  kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\n)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(\n  sum(\n    rate(container_fs_reads_total{namespace=\"$namespace\", container!=\"\"}[5m])\n    *on(namespace, pod) group_left()\r\n\r\n    kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\r\n\r\n  )\n)",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(\n  sum(\n    rate(container_fs_writes_total{namespace=\"$namespace\", container!=\"\"}[5m])\n    *on(namespace, pod) group_left()\r\n\r\n    kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\r\n\r\n  )\n)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"\"}[$__rate_interval])\n  * on (namespace, pod) group_left()\r\r\n  kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\r\n\r\n)",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(\n  rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"\"}[$__rate_interval])\n  * on (namespace, pod) group_left()\r\r\n  kube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}\r\n\r\n)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "description": "파드의 Ephemeral Storage 사용량",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    ephemeral_storage_pod_usage{pod_namespace=\"$namespace\"}\n    , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\"\n  ), \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n)\n* on (namespace, pod)\nkube_pod_labels{namespace=\"$namespace\", label_workspaces_aipub_ten1010_io_owner=\"$workspace\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}