{
 "title": "Ten AIPubJob Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aipubjob_status_state{job=\"aipub-crd-exporter\"}, project)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m" },
   {
    "name": "aipubjob",
    "query": {
     "query": "label_values(aipubjob_status_state{job=\"aipub-crd-exporter\", project=\"$namespace\"}, aipubjob)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AI Pub Job",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipubjob_info{project=\"$namespace\", aipubjob=\"$aipubjob\"}",
     "legendFormat": "{{aipubjob}}"
    }
   ]
  },
  {
   "title": "Project",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipubjob_info{project=\"$namespace\", aipubjob=\"$aipubjob\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  count(aipubjob_spec_cron{project=\"$namespace\", aipubjob=\"$aipubjob\"}), \n  1\n) or vector(0)"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipubjob_status_state{project=\"$namespace\", aipubjob=\"$aipubjob\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Suspend",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aipubjob_spec_suspend{project=\"$namespace\", aipubjob=\"$aipubjob\"}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aipubjob_status_pod{project=\"$namespace\", aipubjob=\"$aipubjob\", phase=\"Pending\"}) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(aipubjob_status_pod{project=\"$namespace\", aipubjob=\"$aipubjob\", phase=\"Running\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(aipubjob_status_pod{project=\"$namespace\", aipubjob=\"$aipubjob\", phase=\"Succeeded\"}) or vector(0)",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(aipubjob_status_pod{project=\"$namespace\", aipubjob=\"$aipubjob\", phase=\"Failed\"}) or vector(0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - aipubjob_created{project=\"$namespace\", aipubjob=\"$aipubjob\"}"
    }
   ]
  },
  {
   "title": "Owned Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n* on (namespace, pod, uid, instance) group_right(owner_kind, owner_name)\nkube_pod_status_phase{namespace=\"$namespace\", pod=~\"$aipubjob.*\"} > 0"
    }
   ]
  },
  {
   "title": "Pod 할당 GPU / MIG 인스턴스",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"}\n    )\n    * on (exported_namespace, exported_pod) group_left(owner_name)\n    label_replace(\n      label_replace(\n        kube_pod_owner{\n          namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n        }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)"
    }
   ]
  },
  { "title": "시스템", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (namespacem, pod, owned_name) (\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$aipubjob.*\", container!=\"\", image!=\"\"}[5m])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$aipubjob.*\", container!=\"\", image!=\"\"}\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"} * 0\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n  + on(UUID, GPU_I_ID) group_left()\n  gpu:resource:gpu_temp\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "description": "GPU  전력 소모량",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"} * 0\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n  + on(UUID, GPU_I_ID) group_left()\n  gpu:resource:power\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"} * 0\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n  + on(UUID, GPU_I_ID) group_left()\n  gpu:resource:util\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "연산 자원의 공간 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"} * 0\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n  + on(UUID, GPU_I_ID) group_left()\n  gpu:resource:sm_active\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "description": "GPU의 연산자원 중 텐서코어의 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"} * 0\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n  + on(UUID, GPU_I_ID) group_left()\n  gpu:resource:tensor_core\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory R/W Utilization",
   "type": "graph",
   "description": "GPU 메모리의 읽고 쓰기 시간을 합한 시간의 비율 \n(GPU Memory bandwidth)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"} * 0\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n  + on(UUID, GPU_I_ID) group_left()\n  gpu:resource:dram_active\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU 메모리 활용 크기",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node, gpu, UUID, GPU_I_ID, GPU_I_PROFILE, modelName, exported_namespace, exported_pod, exported_container) (\n  GPU_POD_MEMORY{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"}\n  * on(exported_namespace, exported_pod, UUID) group_left(gpu, GPU_I_ID, GPU_I_PROFILE, exported_container)\n  sgn(\n    label_replace(\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$aipubjob.*\"}\n      * on (exported_namespace, exported_pod) group_left()\n      label_replace(\n        label_replace(\n          kube_pod_labels{namespace=\"$namespace\", label_aipub_ten1010_io_aipubjob_name=\"$aipubjob\"}\n          , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n      ), \"UUID\", \"$1\", \"MIG_UUID\", \"(.*)\"\n    )\n    or\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod!=\"$aipubjob.*\", UUID=~\"GPU.*\"}\n    * on (exported_namespace, exported_pod) group_left()\n    label_replace(\n      label_replace(\n        kube_pod_labels{namespace=\"$namespace\", label_aipub_ten1010_io_aipubjob_name=\"$aipubjob\"}\n        , \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n    )\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}--({{gpu}})({{gpu_2}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Network Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$aipubjob.*\"}[$__rate_interval])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$aipubjob.*\"}[$__rate_interval])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(\n  sum by (pod) (\n    rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$aipubjob.*\"}[5m])\n    * on (namespace, pod) group_left(owner_name)\n    kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n\r\r\r\r\r  )\n\r\r\r\r\r\r\r)",
     "legendFormat": "(Reads) Pod: {{pod}}"
    },
    {
     "expr": "ceil(\n  sum by (pod) (\n    rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$job_name.*\"}[5m])\n    * on (namespace, pod) group_left(owner_name)\n    kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n  )\n)",
     "legendFormat": "(Writes) Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$aipubjob.*\", container!=\"\"}[5m])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=~\"$aipubjob.*\"}\n)",
     "legendFormat": "(Reads) Pod: {{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$job_name.*\", container!=\"\"}[5m])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "(Writes) Pod: {{pod}}"
    }
   ]
  }
 ]
}