{
 "title": "Ten Cluster Overview",
 "tags": [
  "overview",
  "ten"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "노드",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "Nodes" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_metadata_generation)",
     "legendFormat": "전체 워크로드 수"
    },
    { "expr": "count(kube_job_info)", "legendFormat": "전체 작업 수" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (GPU_TOTAL{is_block=\"false\", node!=\"cluster\"} \n  * on(node) \n  group_left() \n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}) or on() vector(0)\n) + \nsum(\n  (GPU_TOTAL{is_block=\"true\", node!=\"cluster\"} \n  * on(node) \n  group_left() \n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}) or on() vector(0)\n) / 100",
     "legendFormat": "전체 GPU "
    },
    {
     "expr": "sum(\n  (GPU_FREE{is_block=\"false\", node!=\"cluster\"}\n  * on(node)\n  group_left()\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}) or on() vector(0)\n)\n+\nsum(\n  (GPU_FREE{is_block=\"true\", node!=\"cluster\"}\n  * on(node)\n  group_left()\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}) or on() vector(0)\n) / 100",
     "legendFormat": "가용 가능 GPU"
    }
   ]
  },
  {
   "title": "할당 GPU 활용률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(GPU_POD_UTIL)/sum(GPU_POD_UTIL_LIMIT{}))*100",
     "legendFormat": "할당 GPU 활용률"
    }
   ]
  },
  {
   "title": "워크로드 기간 ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort(max by (namespace, pod, deployment_name) (\n  max_over_time(kube_pod_owner{owner_kind=\"ReplicaSet\"}[30d])\n  * on(namespace, owner_name) group_left(deployment_name)\n  max by (namespace, owner_name, deployment_name) (\n    label_replace(\n      label_replace(\n        max_over_time(kube_replicaset_owner{owner_kind=\"Deployment\"}[30d]),\n        \"deployment_name\", \"$1\", \"owner_name\", \"(.+)\"\n      ),\n      \"owner_name\", \"$1\", \"replicaset\", \"(.+)\"\n    )\n  )\n) * on(namespace, pod) group_right(deployment_name) (\n  max by (namespace, pod) (\n    max_over_time(timestamp(kube_pod_created{})[30d:1m])\n    -\n    max_over_time(kube_pod_created{}[30d])\n  )\n)))",
     "legendFormat": "{{deployment_name}}"
    },
    {}
   ]
  },
  {
   "title": "GPU 유휴자원",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  label_replace(\r\n    sum by (name) (\r\n      GPU_FREE{is_block=\"false\", node!=\"cluster\"}\r\n      * on(node)\r\n      group_left()\r\n      kube_node_status_condition{condition=\"Ready\", status=\"true\"}\r\n    ),\r\n    \"name\",\r\n    \"$1\",\r\n    \"name\",\r\n    \"nvidia-(.*)\"\r\n  )\r\n) or (\r\n  label_replace(\r\n    sum by (name) (\r\n      GPU_FREE{is_block=\"true\", node!=\"cluster\"}\r\n      * on(node)\r\n      group_left()\r\n      kube_node_status_condition{condition=\"Ready\", status=\"true\"}\r\n    ),\r\n    \"name\",\r\n    \"block-$1\",\r\n    \"name\",\r\n    \"nvidia-(.*)\"\r\n  )\r\n)",
     "legendFormat": "{{name}}-{{resource}}"
    },
    {
     "expr": "(\r\n  label_replace(\r\n    max by (name) (\r\n      GPU_FREE{is_block=\"false\", node!=\"cluster\"}\r\n      * on(node)\r\n      group_left()\r\n      kube_node_status_condition{condition=\"Ready\", status=\"true\"}\r\n    ),\r\n    \"name\",\r\n    \"$1\",\r\n    \"name\",\r\n    \"nvidia-(.*)\"\r\n  )\r\n) or (\r\n  label_replace(\r\n    max by (name) (\r\n      GPU_FREE{is_block=\"true\", node!=\"cluster\"}\r\n      * on(node)\r\n      group_left()\r\n      kube_node_status_condition{condition=\"Ready\", status=\"true\"}\r\n    ),\r\n    \"name\",\r\n    \"block-$1\",\r\n    \"name\",\r\n    \"nvidia-(.*)\"\r\n  )\r\n)"
    }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "장애 발생 노드",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info)-sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"})\n",
     "legendFormat": "Nodes"
    }
   ]
  },
  { "title": "노드 별 자원 활용률", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (node)",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(\n  GPU_TOTAL{node!=\"cluster\", is_block=\"false\"} \n  * on(node) group_left()\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}\n) by (node)",
     "legendFormat": "GPU Utilization"
    },
    {
     "expr": "sum(GPU_POD_MEMORY{}) by (node)",
     "legendFormat": "GPU Memory Utilization"
    },
    {
     "expr": "sum(\n  GPU_TOTAL{node!=\"cluster\", is_block=\"true\"} /100\n  * on(node) group_left()\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}\n) by (node)"
    },
    { "expr": "sum(GPU_POD_UTIL{}) by (node)" },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{}) by (node)"
    },
    {
     "expr": "sum(GPU_DEVICE_CAPACITY_UTIL{}/100) by (node)"
    }
   ]
  },
  { "title": "네임스페이스 별 자원 활용률", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace)",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(\n  label_replace(\n    GPU_POD_UTIL_LIMIT{},\n    \"namespace\",\n    \"$1\",\n    \"exported_namespace\",\n    \"(.*)\"\n  )/100\n) by (namespace)"
    },
    {
     "expr": "sum(\n  label_replace(\n    GPU_POD_MEMORY{},\n    \"namespace\",\n    \"$1\",\n    \"exported_namespace\",\n    \"(.*)\"\n  )\n) by (namespace)",
     "legendFormat": "GPU Memory Utilization"
    },
    {
     "expr": "sum(\n  label_replace(\n    GPU_POD_UTIL{},\n    \"namespace\",\n    \"$1\",\n    \"exported_namespace\",\n    \"(.*)\"\n  )\n) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{}) by (namespace)"
    },
    {
     "expr": "(\n  sum(\n    kube_pod_container_resource_limits{\n      job=\"kube-state-metrics\",\n      resource=~\".*ten1010_io_gpu_.*\"\n    } * on(pod, namespace) group_left()\n    (kube_pod_status_phase{phase=~\"Running|Created\"} == 1)\n  ) by (namespace)\n)\nor\n(\n  sum(\n    kube_pod_container_resource_limits{\n      job=\"kube-state-metrics\",\n      resource=~\".*ten1010_io_block_.*\"\n    } * on(pod, namespace) group_left()\n    (kube_pod_status_phase{phase=~\"Running|Created\"} == 1)\n  ) by (namespace) / 100\n)"
    }
   ]
  },
  {
   "title": "HiddenPanels(테스트중)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(GPU_DEVICE_CAPACITY_UTIL{}/100)",
       "legendFormat": "전체 GPU 자원"
      },
      {
       "expr": "sum(GPU_DEVICE_CAPACITY_UTIL{}/100)- (sum(GPU_POD_UTIL_LIMIT{}/100) or on() vector(0))",
       "legendFormat": "가용 가능 GPU 자원"
      }
     ]
    },
    {
     "title": "단일/분산 작업 기간 ",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(4, \n  sort(\n    max by (namespace, pod, job_name, owner_kind) (\n      max_over_time(kube_pod_owner{owner_kind=~\"Job|PyTorchJob|MPIJob\"}[30d])\n      * on(namespace, owner_name) group_left(job_name)\n      max by (namespace, owner_name, job_name) (\n        label_replace(\n          max_over_time(kube_pod_owner{owner_kind=~\"Job|PyTorchJob|MPIJob\"}[30d]),\n          \"job_name\", \"$1\", \"owner_name\", \"(.+)\"\n        )\n      )\n    ) * on(namespace, pod) group_right(job_name, owner_kind) (\n      max by (namespace, pod) (\n        max_over_time(timestamp(kube_pod_created{})[30d:1m])\n        -\n        max_over_time(kube_pod_created{}[30d])\n      )\n    )\n  )\n)",
       "legendFormat": "{{job_name}}"
      },
      {}
     ]
    }
   ]
  }
 ]
}