{
 "title": "AIPub Overview",
 "tags": [ "AIpub" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{}, namespace)\n"
    }
   },
   { "name": "duration", "query": "1d,7d,30d,90d,180d,365d" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{}, node)"
    }
   },
   { "name": "gpu_timerange", "query": "7d,30d,90d,180d,365d" }
  ]
 },
 "panels": [
  {
   "title": "컨트롤 플레인",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{role=\"control-plane\"})",
     "legendFormat": "전체"
    }
   ]
  },
  {
   "title": "컨트롤 플레인 상태",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\n  kube_node_role{role=\"control-plane\"}\n  * on(node) group_right()\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}\n)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum (\n  kube_node_role{role=\"control-plane\"}\n  * on(node) group_right()\n  kube_node_status_condition{condition=\"Ready\", status=~\"false|unknown\"}\n) \n",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "클러스터 CPU 사용률",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "클러스터 GPU 할당률",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(\r\n  (kube_pod_container_status_running == 1) * on(pod, namespace, container, uid) group_right()\r\n  (\r\n    max_over_time(gpu:resource:requests{ node!=\"\"}[$__interval])\r\n  )\r\n) or vector(0))\n/\nsum(gpu:resource:node{node!=\"\"})\n\n",
     "legendFormat": "GPU 할당"
    }
   ]
  },
  {
   "title": "CPU 노드",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info)\n- count(count by (Hostname) (DCGM_FI_DEV_GPU_TEMP / DCGM_FI_DEV_GPU_TEMP))"
    }
   ]
  },
  {
   "title": "CPU 노드 상태",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_condition{condition=\"Ready\", status=~\"true\"}\n  * on (node) group_left()\n  kube_node_labels\n unless on (node)\n  label_replace(DCGM_FI_DEV_GPU_TEMP, \"node\", \"$1\", \"Hostname\", \"(.*)\")\n) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(\n  kube_node_status_condition{condition=\"Ready\", status=~\"false|unknown\"}\n  * on (node) group_left()\n  kube_node_labels\n   unless on (node)\n  label_replace(DCGM_FI_DEV_GPU_TEMP, \"node\", \"$1\", \"Hostname\", \"(.*)\")\n) or vector(0)",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "클러스터 메모리 사용률",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{}) / sum(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "GPU 노드",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (Hostname) (DCGM_FI_DEV_GPU_TEMP / DCGM_FI_DEV_GPU_TEMP))",
     "legendFormat": "전체"
    }
   ]
  },
  {
   "title": "GPU 노드 상태",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_condition{condition=\"Ready\", status=~\"true\"}\n  * on (node) group_left()\n  kube_node_labels\n and on (node)\n  label_replace(DCGM_FI_DEV_GPU_TEMP, \"node\", \"$1\", \"Hostname\", \"(.*)\")\n)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(\n  kube_node_status_condition{condition=\"Ready\", status=~\"false|unknown\"}\n  * on (node) group_left()\n  kube_node_labels\n and on (node)\n  label_replace(DCGM_FI_DEV_GPU_TEMP, \"node\", \"$1\", \"Hostname\", \"(.*)\")\n)",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "클러스터 GPU 전력 소비량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max by (Hostname, UUID) (DCGM_FI_DEV_POWER_USAGE{}))"
    }
   ]
  },
  {
   "title": "노드별 CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"})\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "노드별 메모리 사용률",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=\"node-exporter\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=\"node-exporter\"})\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "노드별 루트 디렉토리 사용률",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (max by (instance) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/etc/host\"}) or max by (instance) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"}))\n  -\n  (max by (instance) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/etc/host\"}) or max by (instance) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"}))\n)\n/\n(max by (instance) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/etc/host\"}) or max by (instance) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"}))",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "노드별 GPU 전력 소모량",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by (Hostname) (max by (Hostname, UUID) (DCGM_FI_DEV_POWER_USAGE{}))",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  {
   "title": "노드별 초당 요청 수",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_operation_total{node!=\"\"}[$__range])) by (node)\nor\navg by (node) (\nlabel_replace(\n   (node_memory_MemAvailable_bytes{job=\"node-exporter\"}) * 0,\n  \"node\", \"$1\", \"instance\", \"(.*)\"\n))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "프로젝트별 초당 요청 수",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_operation_total{\n  node=\"\",\n  namespace!~\"^(|aipub.*|coaster|efk|prometheus|linkerd|ingress-nginx|keycloak|kube-flannel|kube-system|kube-public|s3-harbor|project-controller|harbor|kube-node-lease)$\", \n  operation=\"\", \n  deployment=\"\", \n  pod=\"\"\n}[$__range])) by (namespace)\nor\nsum(kube_namespace_created{\n  namespace!~\"^$|aipub.*|coaster|efk|prometheus|linkerd|ingress-nginx|keycloak|kube-flannel|kube-system|kube-public|s3-harbor|project-controller|harbor|kube-node-lease\"\n}) by (namespace) * 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "노드별 상태",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (node) (kube_node_status_condition{condition=\"Ready\", node!=\"\", status=\"false\"}) * -1\n+\nmax by (node) (kube_node_status_condition{condition=\"Ready\", node!=\"\", status=\"true\"}) * 1\n+\nmax by (node) (kube_node_status_condition{condition=\"Ready\", node!=\"\", status=\"unknown\"}) * -1"
    },
    {
     "expr": "1 - max by (node) (kube_node_spec_unschedulable{})"
    },
    {
     "expr": "max by (node) (kube_node_status_condition{condition=\"MemoryPressure\", node!=\"\", status=\"false\"}) * 1\n+\nmax by (node) (kube_node_status_condition{condition=\"MemoryPressure\", node!=\"\", status=\"true\"}) * -1\n+\nmax by (node) (kube_node_status_condition{condition=\"MemoryPressure\", node!=\"\", status=\"unknown\"}) * 2"
    },
    {
     "expr": "max by (node) (kube_node_status_condition{condition=\"DiskPressure\", node!=\"\", status=\"false\"}) * 1\n+\nmax by (node) (kube_node_status_condition{condition=\"DiskPressure\", node!=\"\", status=\"true\"}) * -1\n+\nmax by (node) (kube_node_status_condition{condition=\"DiskPressure\", node!=\"\", status=\"unknown\"}) * 2"
    },
    {
     "expr": "max by (node) (kube_node_status_condition{condition=\"PIDPressure\", node!=\"\", status=\"false\"}) * 1\n+\nmax by (node) (kube_node_status_condition{condition=\"PIDPressure\", node!=\"\", status=\"true\"}) * -1\n+\nmax by (node) (kube_node_status_condition{condition=\"PIDPressure\", node!=\"\", status=\"unknown\"}) * 2"
    },
    {
     "expr": "max by (node) (kube_node_status_condition{condition=\"NetworkUnavailable\", node!=\"\", status=\"false\"}) * 1\n+\nmax by (node) (kube_node_status_condition{condition=\"NetworkUnavailable\", node!=\"\", status=\"true\"}) * -1\n+\nmax by (node) (kube_node_status_condition{condition=\"NetworkUnavailable\", node!=\"\", status=\"unknown\"}) * 2"
    }
   ]
  },
  {
   "title": "노드별 자원",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=~\"cpu\", node!=\"\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=~\"memory\", node!=\"\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)",
     "legendFormat": "GPU Memory Utilization"
    },
    {
     "expr": "(sum(gpu:resource:requests{node!=\"\"}) by (node) or sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)*0 )"
    },
    {
     "expr": "sum(gpu:resource:node{}) by (node) > 0 or sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node) * 0\n"
    },
    {
     "expr": "sum by (node) (\n  kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n  * on(pod) group_left(node) kube_pod_info{node!=\"\"}\n)\nor\nsum by (node) (kube_node_info{node!=\"\"}) * 0"
    }
   ]
  },
  {
   "title": "프로젝트별 자원",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{ resource=\"cpu\"} * on(pod, namespace, container) group_left()\n    (kube_pod_container_status_running == 1)\n   ) by (namespace)\nor\nsum(kube_namespace_created{}) by (namespace)*0"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{ resource=\"memory\"}* on(pod, namespace, container) group_left()\n    (kube_pod_container_status_running == 1)\n   ) by (namespace)\nor\nsum(kube_namespace_created{}) by (namespace)*0"
    },
    {
     "expr": "sum(gpu:resource:requests{ node!=\"\"}) by (namespace) or sum(kube_namespace_created{}) by (namespace)*0\n"
    },
    {
     "expr": "sum by (namespace) (\n   kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n   * on(pod, namespace) group_left(node)\n   kube_pod_info{node!=\"\"}\n)\nor\nsum(kube_namespace_created{}) by (namespace) * 0"
    }
   ]
  }
 ]
}