{
 "title": "Ten Deployment Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m" },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_labels{namespace=\"$namespace\", deployment=\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_labels{namespace=\"$namespace\", deployment=\"$deployment\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "READY",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"$deployment\"}",
     "legendFormat": "READY"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=\"$deployment\"}",
     "legendFormat": "DESIRED"
    }
   ]
  },
  {
   "title": "UP-TO-DATE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_updated{namespace=\"$namespace\", deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_deployment_created{namespace=\"$namespace\", deployment=~\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Owned ReplicaSets",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$deployment\"}\n* on(namespace, replicaset)\nkube_replicaset_status_ready_replicas{namespace=\"proj1\", replicaset=~\"$deployment.*\"}"
    }
   ]
  },
  {
   "title": "Deployment 할당 GPU / MIG 인스턴스",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_pod=~\"$deployment.*\"}\n  )\n)\nor\nsum by (modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  sgn(\n    label_replace(\n      MIG_POD_ALLOCATED{exported_pod=~\"$deployment.*\"},\n      \"node\", \"$1\", \"Hostname\", \"(.+)\"\n    )\n  )\n)"
    }
   ]
  },
  { "title": "시스템", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$deployment.*\"}[5m])\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\", image!=\"\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "description": "GPU  전력 소모량",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:power\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:power\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:util\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$deployment.*\"\n      }\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:util\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      MIG_POD_ALLOCATED{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$deployment.*\"\n      }\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "연산 자원의 공간 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:sm_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:sm_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "description": "GPU의 연산자원 중 텐서코어의 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:tensor_core\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:tensor_core\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory R/W Utilization",
   "type": "graph",
   "description": "GPU 메모리의 읽고 쓰기 시간을 합한 시간의 비율 \n(GPU Memory bandwidth)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:dram_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:dram_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU 메모리 활용 크기",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, UUID, gpu, modelName, GPU_I_PROFILE) (\n  GPU_POD_MEMORY{\n    exported_namespace=\"$namespace\",\n    exported_pod=~\"$deployment.*\"\n  }\n  * on(exported_namespace, exported_pod, UUID) group_left(GPU_I_PROFILE)\n  (\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$deployment.*\"\n      }\n    )\n    unless\n    label_replace(\n      sgn(\n        MIG_POD_ALLOCATED{\n          exported_namespace=\"$namespace\",\n          exported_pod=~\"$deployment.*\"\n        }\n      ),\n      \"UUID\", \"$1\", \"MIG_UUID\", \"(.+)\"\n    )\n    * on (exported_namespace, exported_pod, UUID) group_left()\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$deployment.*\"\n      }\n    )\n  )\n)",
     "legendFormat": "{{exported_pod}}{{modelName}}-({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Network Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$deployment.*\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$deployment.*\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(\n  sum(\n    rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$deployment.*\"}[5m])\n\r\r\r\r\r  )\n\r\r\r\r\r\r\r)",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(\n  sum(\n    rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$deployment.*\"}[5m])\n  )\n)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[5m])\n)",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(\n  rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[5m])\n)",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}