{
 "title": "Ten Operation",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "operation",
    "label": "operation",
    "query": {
     "query": "label_values(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=\"$namespace\"}, label_operation_aipub_ten1010_io_owner)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m" },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"},  horizontalpodautoscaler)\n"
    }
   },
   {
    "name": "hpa_metric",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}, metric_name)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=~\"$namespace\", label_operation_aipub_ten1010_io_owner=~\"$operation\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "레플리카 갯수",
   "type": "stat",
   "description": " 오퍼레이션이 생성할 수 있는 최소/최대 파드(레플리카) 수와 현재 파드(레플리카)의 갯수",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (label_operation_aipub_ten1010_io_owner) (kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\"}\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)\n\r\n\r\n\r\n* on(horizontalpodautoscaler, namespace) group_right(label_operation_aipub_ten1010_io_owner)\r\n(\n\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n))\n",
     "legendFormat": "최소 레플리카"
    },
    {
     "expr": " \r\nmax by (label_operation_aipub_ten1010_io_owner) (kube_deployment_spec_replicas{namespace=\"$namespace\"}\r\n\r\n\r\n* on(deployment) group_left(label_operation_aipub_ten1010_io_owner) (\r\nkube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", deployment=\"$deployment\", namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n) )",
     "legendFormat": "현재 레플리카"
    },
    {
     "expr": "max by (label_operation_aipub_ten1010_io_owner) (kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\"}\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)\n\r\n\r\n\r\n* on(horizontalpodautoscaler) group_right(label_operation_aipub_ten1010_io_owner)\r\n(\n\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))\n",
     "legendFormat": "최대 레플리카"
    }
   ]
  },
  {
   "title": "운영 시간",
   "type": "stat",
   "description": "오퍼레이션이 배포된 후 시간",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  max by (namespace, label_operation_aipub_ten1010_io_owner) (\r\n    last_over_time(timestamp(kube_deployment_created{namespace=\"$namespace\"})[$__range:30s])\r\n   * on(deployment) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", deployment=\"$deployment\", namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n\r\n))\n-\n\r\n\r\nmax by (namespace, label_operation_aipub_ten1010_io_owner) (\r\n    last_over_time(kube_deployment_created{namespace=\"$namespace\"}[$__range])\r\n   * on(deployment) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", deployment=\"$deployment\",  namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n\r\n))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "P50 응답시간",
   "type": "stat",
   "description": "선택된 시간 범위 내 HTTP의 요청에 대한 50%의 응답시간 백분위",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", namespace!=\"\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", namespace!=\"\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 5m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", namespace!=\"\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m])\n)) / 300\r\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근"
    },
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset $__range\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range])\n)) / $__range_s\r\n  )\r\n)\n",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "응답-2XX ,3XX",
   "type": "stat",
   "description": "선택된 시간 범위 내 HTTP 응답들의 상태 유형 2XX,3XX 응답 수 요약",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=~\"$operation\", deployment=~\"$deployment\", pod=\"\", node=\"\", status_code=~\"2.*|3.*\", le=\"+Inf\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=~\"$operation\", deployment=~\"$deployment\", pod=\"\", node=\"\", status_code=~\"2.*|3.*\", le=\"+Inf\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=~\"$operation\", deployment=~\"$deployment\", pod=\"\", node=\"\", status_code=~\"2.*|3.*\", le=\"+Inf\"}[$__range])\n)) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HPA 상태",
   "type": "stat",
   "description": "스케일링 가능 상태 : 스케일링을 위한 메트릭 수집이 가능하여 스케일링이 동작 할수 있는 상태\n\n스케일링 활성화 : 수집된 메트릭을 통해 레플리카의 스케일링이 작동 중인 상태\n\n스케일링 제한됨 : 최대/최소 레플리카수에 도달하여 더이상 스케일링이 불가능한 상태",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=\"$namespace\", condition=\"AbleToScale\", status=\"true\"})\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)  \r\n\r\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))",
     "legendFormat": "스케일 가능 상태(AbleToScale)"
    },
    {
     "expr": "min(\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=\"$namespace\", condition=\"ScalingActive\", status=\"true\"})\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)\r\n\r\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))",
     "legendFormat": "스케일 활성 상태(ScalingActive)"
    },
    {
     "expr": "max(\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=\"$namespace\", condition=\"ScalingLimited\", status=\"true\"})\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n) \r\n\r\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))",
     "legendFormat": "스케일 제한 상태(ScalingLimited)"
    }
   ]
  },
  {
   "title": "HPA 메트릭",
   "type": "table-old",
   "description": "레플리카의 스케일링을 위해 활용되는 메트릭의 기준치와 현재 값 리스트",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(\r\n  (kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\"})\r\n\r\n)\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n)"
    },
    {
     "expr": "(\r\n  (kube_horizontalpodautoscaler_status_target_metric{namespace=\"$namespace\"})\r\n\r\n)\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n)"
    }
   ]
  },
  {
   "title": "P95 응답시간",
   "type": "stat",
   "description": "선택된 시간 범위 내 HTTP의 요청에 대한 95%의 응답시간 백분위",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\",  pod=\"\", node=\"\"} offset 5m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m])\n)) / 300\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range])\n)) / $__range_s\r\n  )\r\n)",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "레플리카 상태",
   "type": "stat",
   "description": "오퍼레이션이 배포한 레플리카 중 서비스 가능한 레플리카와 서비스 불가능한 레플리카 수",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (kube_deployment_status_replicas_available{namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\n* on(deployment) group_right(label_operation_aipub_ten1010_io_owner)\nlabel_replace(\n  kube_deployment_labels{namespace=\"$namespace\", deployment=\"$deployment\", label_operation_aipub_ten1010_io_owner=\"$operation\", job!=\"kubernetes-service-endpoints\"},\n  \"operation\", \"$1\", \"label_operation_aipub_ten1010_io_owner\", \"(.+)\"\n))",
     "legendFormat": "가용"
    },
    {
     "expr": "sum by (operation) (kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\n* on(deployment) group_right(label_operation_aipub_ten1010_io_owner)\nlabel_replace(\n  kube_deployment_labels{namespace=\"$namespace\", label_operation_aipub_ten1010_io_owner=\"$operation\", deployment=\"$deployment\", job!=\"kubernetes-service-endpoints\"},\n  \"operation\", \"$1\", \"label_operation_aipub_ten1010_io_owner\", \"(.+)\"\n))",
     "legendFormat": "비가용"
    }
   ]
  },
  {
   "title": "초 당 요청수",
   "type": "stat",
   "description": "최근 및 선택된 시간 범위(구간)에 대한 초당 평균 HTTP 요청 수",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]) -   \n(\r\n    request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 5m\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m])\n)) / 300)",
     "legendFormat": "최근"
    },
    {
     "expr": "sum((max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"$namespace\", deployment=\"$deployment\", operation=\"$operation\", pod=\"\", node=\"\"}[$__range])\n)) / $__range_s)",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "누적요청건수",
   "type": "stat",
   "description": "최근 및 선택된 시간 범위(구간) 동안의 HTTP 요청의 합",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max_over_time(request_operation_total{namespace=\"$namespace\", deployment=\"$deployment\", operation=\"$operation\", pod=\"\", node=\"\"}[1h]) -   \n(\r\n    request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 1h\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", deployment=\"$deployment\",pod=\"\", node=\"\"}[1h])\n))",
     "legendFormat": "1시간"
    },
    {
     "expr": "sum (max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"$namespace\", deployment=\"$deployment\", operation=\"$operation\", pod=\"\", node=\"\"}[$__range])\n))",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "P99 응답시간",
   "type": "stat",
   "description": "선택된 시간 범위 내 HTTP의 요청에 대한 99%의 응답시간 백분위",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 5m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m])\n)) / 300\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\",  pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range])\n)) / $__range_s\r\n  )\r\n)\n",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "응답-4XX,5XX",
   "type": "stat",
   "description": "선택된 시간 범위 내 HTTP 응답들의 상태 유형 4XX,5XX 응답 수 요약",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=~\"$operation\", deployment=~\"$deployment\",  pod=\"\", node=\"\", status_code=~\"4.*|5.*\", le=\"+Inf\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=~\"$operation\", pod=\"\", deployment=~\"$deployment\", node=\"\", status_code=~\"4.*|5.*\", le=\"+Inf\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=~\"$operation\", deployment=~\"$deployment\", pod=\"\", node=\"\", status_code=~\"4.*|5.*\", le=\"+Inf\"}[$__range])\n)) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "P9999 응답시간",
   "type": "stat",
   "description": "선택된 시간 범위 내 HTTP의 요청에 대한 99.99%의 응답시간 백분위",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 5m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\",  pod=\"\", node=\"\"}[5m])\n)) \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근"
    },
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le, operation) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[$__range])\n)) / $__range_s\r\n  )\r\n)\n\n\r\r",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "요약 타임라인",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "heatmap",
     "description": "오퍼레이션의 상태에 대한 시간변화 (초록색이 진할 수록 정상 레플리카의 수가 많다.)",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "\nmax by (label_operation_aipub_ten1010_io_owner, namespace) \n(\n(((kube_deployment_status_replicas_available{ app_kubernetes_io_instance=\"\", deployment=\"$deployment\", namespace=\"$namespace\"}) == (kube_deployment_status_replicas{ app_kubernetes_io_instance=\"\", namespace=\"$namespace\"}))*0+2)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\"}\n  )\n)\n)\nor\nmax by (label_operation_aipub_ten1010_io_owner, namespace) \n(\n(((kube_deployment_status_replicas_unavailable{ app_kubernetes_io_instance=\"\", deployment=\"$deployment\", namespace=\"$namespace\"}) == (kube_deployment_status_replicas{ app_kubernetes_io_instance=\"\", deployment=\"$deployment\", namespace=\"$namespace\"}))*0-1)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\"}\n  )\n)\n) \nor\nmax by (label_operation_aipub_ten1010_io_owner, namespace) \n(\n(((kube_deployment_status_replicas_unavailable{ app_kubernetes_io_instance=\"\", namespace=\"$namespace\", deployment=\"$deployment\"} < kube_deployment_status_replicas{ app_kubernetes_io_instance=\"\", namespace=\"$namespace\", deployment=\"$deployment\"}))*0+1)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\"}\n  )\n)\n) \n",
       "legendFormat": "오퍼레이션 상태"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "초당 요청 수 (빨간색일수록 요청수가 많고, 초록색일 수록 요청수가 적다, 요청이 없는 경우 표시되지 않음)",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (operation, namespace) (\nincrease(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]))",
       "legendFormat": "RPS"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "오퍼레이션의 갯수에 대한 시간변화 (붉은색이 진할 수록 레플리카의 수가 많다.)",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "\nmax by (label_operation_aipub_ten1010_io_owner, namespace) \n(\n((kube_deployment_status_replicas_available{ app_kubernetes_io_instance=\"\", namespace=\"$namespace\", deployment=\"$deployment\"}))\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner=\"$operation\"}\n  )\n)\n)",
       "legendFormat": "오퍼레이션 레플리카"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "50% 응답 백분위 (빨간색일수록 응답시간이 느리고, 초록색일수록 빠르다, 요청이 없는 경우 표시되지 않음)",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5,\r\nsum by (operation, namespace, le) (\nincrease(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[5m]))\n)",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "HPA 확장 가능 상태에 대한 변화 (초록색인 경우 확장 가능 상태)",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "min by (label_operation_aipub_ten1010_io_owner, namespace) (\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=\"$namespace\", condition=\"AbleToScale\", status=\"true\"})\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)  \r\n\r\n\r\n* on(horizontalpodautoscaler, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))",
       "legendFormat": "HPA 확장가능"
      },
      {}
     ]
    },
    {
     "type": "heatmap",
     "description": "95% 응답 백분위 (빨간색일수록 응답시간이 느리고, 초록색일수록 빠르다, 요청이 없는 경우 표시되지 않음)",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\r\nsum by (operation, namespace, le) (\nincrease(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", pod=\"\", deployment=\"$deployment\", node=\"\"}[5m]))\n)",
       "legendFormat": "P95"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "HPA 확장 활성 상태에 대한 변화 (초록색인 경우 확장 활성 상태)",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "min by (label_operation_aipub_ten1010_io_owner, namespace) (\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=\"$namespace\", condition=\"ScalingActive\", status=\"true\"})\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)  \r\n\r\n\r\n* on(horizontalpodautoscaler, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))",
       "legendFormat": "HPA 확장활성"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "99% 응답 백분위 (빨간색일수록 응답시간이 느리고, 초록색일수록 빠르다, 요청이 없는 경우 표시되지 않음)",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\r\nsum by (operation, namespace, le) (\nincrease(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=\"$operation\", pod=\"\", deployment=\"$deployment\", node=\"\"}[5m]))\n)",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "type": "heatmap",
     "description": "HPA 확장 제한 상태에 대한 변화 (빨간색인 경우 확장 제한)",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "min by (label_operation_aipub_ten1010_io_owner, namespace) (\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=~\"$namespace\", condition=\"ScalingLimited\", status=\"true\"})\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)  \r\n\r\n\r\n* on(horizontalpodautoscaler, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n))",
       "legendFormat": "HPA 확장 제한"
      },
      {}
     ]
    },
    {
     "type": "heatmap",
     "description": "실패 응답의 수 (빨간색일수록 실패 응답이 많고, 초록색일수록 적다, 실패 응답이 없는 경우 표시되지 않음)",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum by (operation, namespace) (increase(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\", status_code=~\"4.*|5.*\", le=\"+Inf\"}[5m]))",
       "legendFormat": "실패응답"
      }
     ]
    }
   ]
  },
  { "title": "시스템", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (namespace, pod)\n* on(pod) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (namespace, pod)\n*on(pod) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sum( gpu:resource:gpu_temp * on(UUID, GPU_I_ID) group_left(exported_pod, exported_namespace, exported_container) sgn(MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"})) by (exported_pod, modelName, gpu, GPU_I_PROFILE)\nor\n \n(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"} * 0 \n  + on(UUID, GPU_I_ID) \n  group_left() \n  gpu:resource:gpu_temp\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "description": "GPU  전력 소모량",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum( gpu:resource:power * on(UUID, GPU_I_ID) group_left(exported_pod, exported_namespace, exported_container) sgn(MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"})) by (exported_pod, modelName, gpu, GPU_I_PROFILE)\nor\n(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"} * 0 \n  + on(UUID, GPU_I_ID) \n  group_left() \n  gpu:resource:power\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "연산 자원의 시간 활용률",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum( gpu:resource:util * on(UUID, GPU_I_ID) group_left(exported_pod, exported_namespace, exported_container) sgn(MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"})) by (exported_pod, modelName, gpu, GPU_I_PROFILE) / 100.0\nor\n(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"} * 0 \n  + on(UUID, GPU_I_ID) \n  group_left() \n  gpu:resource:util\n) / 100.0",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "연산 자원의 공간 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum( gpu:resource:sm_active * on(UUID, GPU_I_ID) group_left(exported_pod, exported_namespace, exported_container) sgn(MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"})) by (exported_pod, modelName, gpu, GPU_I_PROFILE) \nor\n(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"} * 0 \n  + on(UUID, GPU_I_ID) \n  group_left() \n  gpu:resource:sm_active\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "description": "GPU의 연산자원 중 텐서코어의 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(  gpu:resource:tensor_core  * on(UUID, GPU_I_ID) group_left(exported_pod, exported_namespace, exported_container) sgn(MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"})) by (exported_pod, modelName, gpu, GPU_I_PROFILE)\nor\n(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"} * 0 \n  + on(UUID, GPU_I_ID) \n  group_left() \n  gpu:resource:tensor_core\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory R/W Utilization",
   "type": "graph",
   "description": "GPU 메모리의 읽고 쓰기 시간을 합한 시간의 비율",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum( gpu:resource:dram_active * on(UUID, GPU_I_ID) group_left(exported_pod, exported_namespace, exported_container) sgn(MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"})) by (exported_pod, modelName, gpu, GPU_I_PROFILE)\nor\n(\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\"} * 0 \n  + on(UUID, GPU_I_ID) \n  group_left() \n  gpu:resource:dram_active\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU 메모리 활용 크기",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, UUID, gpu, modelName, GPU_I_PROFILE) (\n  GPU_POD_MEMORY{\n    exported_namespace=\"$namespace\",\n    exported_pod=~\"$deployment.*\"\n  }\n  * on(exported_namespace, exported_pod, UUID) group_left(GPU_I_PROFILE)\n  (\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$deployment.*\"\n      }\n    )\n    unless\n    label_replace(\n      sgn(\n        MIG_POD_ALLOCATED{\n          exported_namespace=\"$namespace\",\n          exported_pod=~\"$deployment.*\"\n        }\n      ),\n      \"UUID\", \"$1\", \"MIG_UUID\", \"(.+)\"\n    )\n    * on (exported_namespace, exported_pod, UUID) group_left()\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$deployment.*\"\n      }\n    )\n  )\n)",
     "legendFormat": "{{exported_pod}}{{modelName}}-({{gpu_2}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Network Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (irate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])\n*on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (irate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__rate_interval])\n*on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\",}[5m])\n*on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)))",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(sum (rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\",}[5m])\n*on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\"}[5m])\n*on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)\n)",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{container!=\"\", namespace=~\"$namespace\"}[5m])\n*on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=~\"$operation\", namespace=~\"$namespace\"}\r\n\r\n)\n)",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "요청", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "요청 분배 비율 ",
   "type": "piechart",
   "description": "각 레플리카에 전달되는 요청의 분배 비율",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod!=\"\", node=\"\"}[$__range]) -   \n(\r\n    request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\",  pod!=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\",  pod!=\"\", node=\"\"}[$__range])\n) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "초 당 요청수",
   "type": "graph",
   "description": "초당 요청 수 기준치 및 초당 요청 수의 시간에 따른 변화 정보",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\n(\r\n  (kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\", metric_name=\"rps\"})\r\n\r\n)\n* on(horizontalpodautoscaler, namespace) group_left()\n(\n  kube_horizontalpodautoscaler_info{scaletargetref_name=\"$deployment\"}\n)\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\"}\r\n)",
     "legendFormat": "Target RPS"
    },
    {
     "expr": "sum((max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[1m]) -   \n(\r\n    request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 1m\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[1m])\n))) / (60*sum by (operation) (kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$deployment\", job!=\"kubernetes-service-endpoints\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "요청건수($interval)",
   "type": "graph",
   "description": "30초 주기로 갱신되는 각 레플리카에 전달된 요청 건수",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, pod) (\r\n  (request_total{namespace=\"$namespace\", pod=~\"$deployment.*\", direction=\"inbound\", target_port!=\"4191\"}) \n\r\n\r\n  or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0))\r\n- (sum by (namespace, pod) (\r\n  (request_total{namespace=\"$namespace\", pod=~\"$deployment.*\", direction=\"inbound\", target_port!=\"4191\"} offset $interval) \n\r\n\r\nor kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0)) > 0 ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "누적요청건수",
   "type": "graph",
   "description": "30초 주기로 갱신되는 누적 요청 건수",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "\rrequest_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} ",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "응답 시간", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "응답시간 분포",
   "type": "piechart",
   "description": "설정된 시간 구간 내 각 응답 시간 별 응답의 분포 비율",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1\", pod=\"\", node=\"\"}[$__range])\n)\n)\n",
     "legendFormat": "<1ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "1-5ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "5-10ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "10-50ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"100\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"100\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"100\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "50-100ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"500\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"500\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"500\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"100\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"100\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"100\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "100-500ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"500\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"500\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"500\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "1000-500ms"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"1000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "1-5s"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"5000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "5-10s"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"10000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "10-50s"
    },
    {
     "expr": "sum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"+Inf\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"+Inf\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"+Inf\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\", operation=~\"$operation\", deployment=\"$deployment\", le=\"50000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "50s-Inf"
    }
   ]
  },
  {
   "title": "응답 시간(백분위수)",
   "type": "graph",
   "description": "응답 시간을 백분위로 분석했을때, 응답 시간의 변화 추이",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"} offset 30s\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P9999"
    }
   ]
  },
  {
   "title": "응답시간($interval)",
   "type": "graph",
   "description": "30초 주기로 갱신되는 각 레플리카 별 평균 응답 시간",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "((\r\nsum by (pod, namespace) (response_latency_ms_sum{namespace=\"$namespace\", pod=~\"$deployment.*\",  direction=\"inbound\", target_port!=\"4191\"} or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0 )\r\n-\r\nsum by (pod, namespace) ((response_latency_ms_sum{namespace=\"$namespace\", pod=~\"$deployment.*\",  direction=\"inbound\", target_port!=\"4191\"} offset $interval) or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0)\r\n)>0)\r\n\r\n/\n((sum by (pod, namespace) (response_latency_ms_count{namespace=\"$namespace\", pod=~\"$deployment.*\",  direction=\"inbound\", target_port!=\"4191\"} or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0 )) - (sum by (pod, namespace) ((response_latency_ms_count{namespace=\"$namespace\", pod=~\"$deployment.*\",  direction=\"inbound\", target_port!=\"4191\"} offset $interval) or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0 )))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "응답과대지연 건수(>50초)",
   "type": "graph",
   "description": "응답에 걸리는 시간이 50초를 초과한 경우의 응답 건수",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (\r\n  (response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"+Inf\", target_port!=\"4191\"}\r\n  - ignoring(le)\r\n  response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"50000\", target_port!=\"4191\"})\n  or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0 \r\n)\n- sum by (pod) (\r\n  (response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"+Inf\", target_port!=\"4191\"} offset $interval\n  - ignoring(le)\r\n  response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"50000\", target_port!=\"4191\"} offset $interval)\n  or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0 \r\n)\n)\n* on(pod) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{pod=~\"$deployment.*\", label_operation_aipub_ten1010_io_owner=\"$operation\", namespace=\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "응답 상태", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "응답 코드 비율",
   "type": "piechart",
   "description": "설정된 시간 구간 내 응답 코드의 분포 비율",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\", le=\"+Inf\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\", le=\"+Inf\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",operation=\"$operation\", deployment=\"$deployment\", pod=\"\", node=\"\", le=\"+Inf\"}[$__range])\n)) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "응답성공건수($interval)",
   "type": "graph",
   "description": "30초 주기로 갱신되는 응답 성공(2XX, 3XX) 건수",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$deployment.*\", direction=\"inbound\", le=\"+Inf\", status_code=~\"2.*\", target_ip!=\"0.0.0.0\"} or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0) - sum by (namespace, pod) ((response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$deployment.*\", direction=\"inbound\", le=\"+Inf\", status_code=~\"2.*\", target_ip!=\"0.0.0.0\"} offset $interval) or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0\n) > 0\n\r\n\r\n\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "응답실패건수($interval)",
   "type": "graph",
   "description": "30초 주기로 갱신되는 응답 실패(4XX, 5XX) 건수",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$deployment.*\", direction=\"inbound\", le=\"+Inf\", status_code!~\"2.*\", target_ip!=\"0.0.0.0\"} or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0) - sum by (namespace, pod) ((response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$deployment.*\", direction=\"inbound\", le=\"+Inf\", status_code!~\"2.*\", target_ip!=\"0.0.0.0\"} offset $interval) or kube_pod_created{namespace=\"$namespace\", pod=~\"$deployment.*\"}*0\n) > 0\n\r\n\r\n\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}