{
 "title": "Node monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\", sysname!=\"Darwin\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "노드 요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Node",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{os_image}}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{kernel_version}}"
    }
   ]
  },
  {
   "title": "Container Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{container_runtime_version}}"
    }
   ]
  },
  {
   "title": "Nvidia Driver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[1m]))) * 100"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"})) * 100"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (Hostname) (DCGM_FI_DEV_GPU_UTIL{Hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"$node\"} / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"$node\"})) * 100"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{name=\"PWR_SYSTEM\", instance=\"$node\"}"
    }
   ]
  },
  { "title": "시스템 상세", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=\"$node\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"$node\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=\"$node\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"$node\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"$node\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"$node\"})\n)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$node\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$node\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$node\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$node\"}\n)",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$node\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$node\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$node\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "System Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_power_watts{name=\"PWR_SYSTEM\", instance=\"$node\"}",
     "legendFormat": "power"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "MIG 인스턴스 추적 불가",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"$node\", mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$node\", mountpoint=\"/\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"$node\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"$node\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Ethernet Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"$node\", device!~\"^v.*|^br.*\"}[$__rate_interval])\r",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Ethernet Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"$node\", device!~\"^v.*|^br.*\"}[$__rate_interval])\r",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Infiniband Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_received_bytes_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Infiniband Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_transmitted_bytes_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "GPU 상세", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "GPU SM Active Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_PROF_SM_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU SM Occupancy Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_OCCUPANCY{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_PROF_SM_OCCUPANCY{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Memory Copy Utilization",
   "type": "graph",
   "description": "MIG 인스턴스 추적 불가",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU GR Active Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Tensor Active Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU DRAM Active Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_DRAM_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_PROF_DRAM_ACTIVE{Hostname=\"$node\", GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=\"$node\",GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{Hostname=\"$node\",GPU_I_PROFILE=\"\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  { "title": "GPU 통신", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "GPU PCIe Receive",
   "type": "graph",
   "description": "MIG 인스턴스 추적 불가",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_PROF_PCIE_RX_BYTES{Hostname=\"$node\",GPU_I_PROFILE=\"\"}[1m])",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "rate(DCGM_FI_PROF_PCIE_RX_BYTES{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}[1m])",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU PCIe Transmit",
   "type": "graph",
   "description": "MIG 인스턴스 추적 불가",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_PROF_PCIE_TX_BYTES{Hostname=\"$node\",GPU_I_PROFILE=\"\"}[1m])",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "rate(DCGM_FI_PROF_PCIE_TX_BYTES{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}[1m])",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU NVLink Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=\"$node\",GPU_I_PROFILE=\"\"}[1m])",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}[1m])",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  { "title": "GPU 안정성", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "GPU XID Error (Normal)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{Hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "GPU PCIe Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_PCIE_REPLAY_COUNTER{Hostname=\"$node\",GPU_I_PROFILE=\"\"}[5m])",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "rate(DCGM_FI_DEV_PCIE_REPLAY_COUNTER{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}[5m])",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  },
  {
   "title": "GPU Energy Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "yaxes": [
    { "format": "joule" }
   ],
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=\"$node\",GPU_I_PROFILE=\"\"}[1m]) / 1000",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "rate(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=\"$node\",GPU_I_PROFILE!=\"\"}[1m]) / 1000",
     "legendFormat": "GPU {{gpu}} / {{GPU_I_ID}} ({{GPU_I_PROFILE}})"
    }
   ]
  }
 ]
}