{
 "title": "Ten Pod Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, pod)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m" },
   {
    "name": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}, pod_ip)"
    }
   },
   {
    "name": "reason",
    "query": {
     "query": "label_values(kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\"}, reason)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod, namespace) (\n  (kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=~\"$pod\", reason=~\"CrashLoopBackOff|ImagePullBackOff|ErrImagePull\"} * 3)\n  or (kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"} * 5)\n  or (kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"} * 3)\n  or (kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"} * 4)\n  or (kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"} * 2)\n  or (kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"} * 1)\n)"
    }
   ]
  },
  {
   "title": "Reason",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Restarts total"
    }
   ]
  },
  {
   "title": "IP address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"},\n  \"pod_ip\",\n  \"N/A\",\n  \"pod_ip\",\n  \"\"\n)",
     "legendFormat": "{{pod_ip}}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_created{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod 할당 GPU / MIG 인스턴스",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)\nor\nsum by (modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)"
    }
   ]
  },
  { "title": "시스템", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}[5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "description": "GPU  전력 소모량",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:power\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:power\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:util\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=\"$pod\"\n      }\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:util\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      MIG_POD_ALLOCATED{\n        exported_namespace=\"$namespace\",\n        exported_pod=\"$pod\"\n      }\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "연산 자원의 공간 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:sm_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:sm_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "description": "GPU의 연산자원 중 텐서코어의 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, exported_container, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:tensor_core\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}\n  )\n)\nor\nsum by (exported_pod, exported_container, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:tensor_core\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}\n  )\n)",
     "legendFormat": "{{exported_container}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory R/W Utilization",
   "type": "graph",
   "description": "GPU 메모리의 읽고 쓰기 시간을 합한 시간의 비율 \n(GPU Memory bandwidth)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:dram_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:dram_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$pod\"}\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU 메모리 활용 크기",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, UUID, gpu, modelName, GPU_I_PROFILE) (\n  GPU_POD_MEMORY{\n    exported_namespace=\"$namespace\",\n    exported_pod=\"$pod\"\n  }\n  * on(exported_namespace, exported_pod, UUID) group_left(GPU_I_PROFILE)\n  (\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=\"$pod\"\n      }\n    )\n    unless\n    label_replace(\n      sgn(\n        MIG_POD_ALLOCATED{\n          exported_namespace=\"$namespace\",\n          exported_pod=\"$pod\"\n        }\n      ),\n      \"UUID\", \"$1\", \"MIG_UUID\", \"(.+)\"\n    )\n    * on (exported_namespace, exported_pod, UUID) group_left()\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=\"$pod\"\n      }\n    )\n  )\n)",
     "legendFormat": "{{exported_pod}}{{modelName}}-({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Network Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (\n  irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (\n  irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(\n  sum(\n    rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=\"$pod\"}[5m])\n\r\r\r\r\r  )\n\r\r\r\r\r\r\r)",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(\n  sum(\n    rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", pod=\"$pod\"}[5m])\n  )\n)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=\"$pod\", container!=\"\"}[5m])\n)",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(\n  rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=\"$pod\", container!=\"\"}[5m])\n)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage",
   "type": "graph",
   "description": "파드의 Ephemeral Storage 사용량",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ephemeral_storage_pod_usage{pod_namespace=\"$namespace\", pod_name=\"$pod\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}