{
 "title": "Ten Operation Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{}, namespace)\n"
    }
   },
   { "name": "duration", "query": "1d,7d,30d,90d,180d,365d" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "전체 Operation 수",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (label_operation_aipub_ten1010_io_owner, namespace)(\n    kube_deployment_created{}\n    * on(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n    (\n      kube_deployment_labels{namespace=~\"$namespace\", label_operation_aipub_ten1010_io_owner!=\"\"}\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "HPA 연동 Operation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  (kube_horizontalpodautoscaler_info{namespace=~\"$namespace\"})\r\n\r\n\r\n* on(horizontalpodautoscaler, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\"}\r\n))"
    }
   ]
  },
  {
   "title": "전체 요청 수",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max_over_time(request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", node=\"\"}[$__range]) -   \n(\r\n    request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", node=\"\"}[$__range])\n))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "P50 응답시간",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 1m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근 "
    },
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "운영시간 Top 5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " topk(5, \nsort_desc(\nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n((\ntimestamp(kube_deployment_created{namespace=~\"$namespace\"})\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n  (kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"})\n  )\n) \n-\n(\nkube_deployment_created{namespace=~\"$namespace\"}\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n  (kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"})\n  )\n) )\n*\non (deployment, namespace) group_left(start_time)\n(\ncount_values without() (\"start_time\", \nmax by (namespace, deployment) \n((\nkube_deployment_created{}\n)*1000\n)\n)\n)\n* on (deployment, namespace) group_left(end_time)\n(\ncount_values without() (\"end_time\", \nmax by (namespace, deployment) \n(((\ntimestamp(kube_deployment_created{})\n)*1000\n)\n\n)\n)\n)\n)\n)\n\n",
     "legendFormat": "{{namespace}}-{{label_operation_aipub_ten1010_io_owner}}"
    }
   ]
  },
  {
   "title": "GPU 자원 점유량 Top 5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc((\nmax by (namespace, label_operation_aipub_ten1010_io_owner)(\r\n(kube_pod_container_resource_limits{ resource=~\"ten1010_io_block.*\", namespace=~\"$namespace\"})\r\n*\r\non (pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\r\n\r\n)\r\n) / 100\nor\nmax by (namespace, label_operation_aipub_ten1010_io_owner)(\r\n(kube_pod_container_resource_limits{ resource=~\"ten1010_io_gpu.*\", namespace=~\"$namespace\"})\r\n*\r\non (pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\r\n\r\n)\r\n)\n)\n\r\n\r\r\r\n*\nmax by (label_operation_aipub_ten1010_io_owner, namespace) \n(\n((kube_deployment_status_replicas_available{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}))\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n  )\n)\n)))\n*\non(label_operation_aipub_ten1010_io_owner, namespace) group_left(deployment)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n  )\n)\n*\non (deployment, namespace) group_left(start_time)\n(\ncount_values without() (\"start_time\", \nmax by (namespace, deployment) (kube_deployment_created{}*1000)\n)\n)\n* on (deployment, namespace) group_left(end_time)\n(\n  count_values without() (\"end_time\", \n    max by (namespace, deployment) (timestamp(kube_deployment_created{})*1000)\n  )\n)",
     "legendFormat": "{{namespace}}-{{label_operation_aipub_ten1010_io_owner}}"
    }
   ]
  },
  {
   "title": "P95응답시간",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 1m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근 "
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "Operation 상태",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    (kube_deployment_status_replicas_available{} == kube_deployment_status_replicas{})\n    * on(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n    (\n      kube_deployment_labels{namespace=~\"$namespace\", label_operation_aipub_ten1010_io_owner!=\"\"}\n    )\n  )\n) or\nvector(0)",
     "legendFormat": "정상"
    },
    {
     "expr": "(count(\n  (\n    (kube_deployment_status_replicas_available{} < kube_deployment_status_replicas{})\n    * on(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n    (\n      kube_deployment_labels{namespace=~\"$namespace\",  label_operation_aipub_ten1010_io_owner!=\"\"}\n    )\n  )\n)\n) ",
     "legendFormat": "주의_Pre"
    },
    {
     "expr": "count(\n  (\n    (kube_deployment_status_replicas_unavailable{} == kube_deployment_status_replicas{} and kube_deployment_status_replicas{} > 0)\n    * on(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n    (\n      kube_deployment_labels{namespace=~\"$namespace\",  label_operation_aipub_ten1010_io_owner!=\"\"}\n    )\n  )\n) or vector(0)",
     "legendFormat": "위험"
    }
   ]
  },
  {
   "title": "HPA 상태",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nmin by (label_operation_aipub_ten1010_io_owner) (\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=~\"$namespace\", condition=\"AbleToScale\", status=\"true\"})\r\n\r\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\"}\r\n)))",
     "legendFormat": "확장 가능"
    },
    {
     "expr": "sum (\nmin by (label_operation_aipub_ten1010_io_owner) (\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=~\"$namespace\", condition=\"ScalingActive\", status=\"true\"})\r\n\r\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\"}\r\n)))",
     "legendFormat": "확장 활성화"
    },
    {
     "expr": "sum (\nmax by (label_operation_aipub_ten1010_io_owner) (\r\n  (kube_horizontalpodautoscaler_status_condition{namespace=~\"$namespace\", condition=\"ScalingLimited\", status=\"true\"})\r\n\r\n\r\n* on(horizontalpodautoscaler) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  kube_horizontalpodautoscaler_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\"}\r\n)))",
     "legendFormat": "확장 제한"
    }
   ]
  },
  {
   "title": "성공 / 실패 요청 수",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max_over_time(response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", status_code=~\"2.*|3.*\", le=\"+Inf\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", status_code=~\"2.*|3.*\",  le=\"+Inf\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", status_code=~\"2.*|3.*\",  le=\"+Inf\"}[$__range])\n))",
     "legendFormat": "성공 요청 수"
    },
    {
     "expr": "sum (max_over_time(response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", status_code=~\"4.*|5.*\", le=\"+Inf\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", status_code=~\"4.*|5.*\",  le=\"+Inf\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\", status_code=~\"4.*|5.*\",  le=\"+Inf\"}[$__range])\n))",
     "legendFormat": "실패 요청 수"
    }
   ]
  },
  {
   "title": "P99 응답시간",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 1m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근 "
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "P9999 응답시간",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 1m\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[1m])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "최근 "
    },
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "구간"
    }
   ]
  },
  {
   "title": "오퍼레이션 리스트",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by (namespace, deployment, label_operation_aipub_ten1010_io_owner)(\nmax_over_time(kube_pod_container_resource_limits{ resource=~\"cpu\", namespace=~\"$namespace\"}[$__range])\n*\non (pod, namespace) group_left(deployment)\n(\nmax by (pod, namespace, owner_name) (\nmax_over_time(kube_pod_owner{owner_kind=\"ReplicaSet\", namespace=~\"$namespace\"}[$__range])\n)\n* on(owner_name) group_left(deployment)\nlabel_replace(\n  label_replace(\n    max by(owner_name, replicaset) (\n      max_over_time(kube_replicaset_owner{owner_kind=\"Deployment\", namespace=~\"$namespace\"}[$__range])\n    ),\n    \"deployment\", \"$1\", \"owner_name\", \"(.+)\"\n  ),\n  \"owner_name\", \"$1\", \"replicaset\", \"(.+)\"\n)\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)\nor \nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\nmax_over_time(kube_deployment_created{namespace=~\"$namespace\"}[$__range])\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)* 0-1 ",
     "legendFormat": "CPU "
    },
    {
     "expr": "max by (namespace, deployment, label_operation_aipub_ten1010_io_owner)(\nmax_over_time(kube_pod_container_resource_limits{ resource=~\"memory\", namespace=~\"$namespace\"}[$__range])\n*\non (pod, namespace) group_left(deployment)\n(\nmax by (pod, namespace, owner_name) (\nmax_over_time(kube_pod_owner{owner_kind=\"ReplicaSet\", namespace=~\"$namespace\"}[$__range])\n)\n* on(owner_name) group_left(deployment)\nlabel_replace(\n  label_replace(\n    max by(owner_name, replicaset) (\n      max_over_time(kube_replicaset_owner{owner_kind=\"Deployment\", namespace=~\"$namespace\"}[$__range])\n    ),\n    \"deployment\", \"$1\", \"owner_name\", \"(.+)\"\n  ),\n  \"owner_name\", \"$1\", \"replicaset\", \"(.+)\"\n)\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)\nor \nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\nmax_over_time(kube_deployment_created{namespace=~\"$namespace\"}[$__range])\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)* 0-1",
     "legendFormat": "Memory"
    },
    {
     "expr": "\r\nmax by (namespace, deployment, label_operation_aipub_ten1010_io_owner)(\r\nmax_over_time(gpu:resource:requests{ resource=~\"ten1010_io_gpu.*\", namespace=~\"$namespace\"}[$__range])\r\n*\r\non (pod, namespace) group_left(deployment)\r\n(\r\nmax by (pod, namespace, owner_name) (\r\nmax_over_time(kube_pod_owner{owner_kind=\"ReplicaSet\"}[$__range])\r\n)\r\n* on(owner_name) group_left(deployment)\r\nlabel_replace(\r\n  label_replace(\r\n    max by(owner_name, replicaset) (\r\n      max_over_time(kube_replicaset_owner{owner_kind=\"Deployment\"}[$__range])\r\n    ),\r\n    \"deployment\", \"$1\", \"owner_name\", \"(.+)\"\r\n  ),\r\n  \"owner_name\", \"$1\", \"replicaset\", \"(.+)\"\r\n)\r\n)\r\n*\r\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\r\n    max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\r\n  )\r\n)\r\n) \r\nor\r\nmax by (namespace, deployment, label_operation_aipub_ten1010_io_owner)(\r\nmax_over_time(kube_pod_container_resource_limits{ resource=~\"cpu\", namespace=~\"$namespace\"}[$__range])\r\n*\r\non (pod, namespace) group_left(deployment)\r\n(\r\nmax by (pod, namespace, owner_name) (\r\nmax_over_time(kube_pod_owner{owner_kind=\"ReplicaSet\"}[$__range])\r\n)\r\n* on(owner_name) group_left(deployment)\r\nlabel_replace(\r\n  label_replace(\r\n    max by(owner_name, replicaset) (\r\n      max_over_time(kube_replicaset_owner{owner_kind=\"Deployment\"}[$__range])\r\n    ),\r\n    \"deployment\", \"$1\", \"owner_name\", \"(.+)\"\r\n  ),\r\n  \"owner_name\", \"$1\", \"replicaset\", \"(.+)\"\r\n)\r\n)\r\n*\r\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\r\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\r\n    max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\r\n  )\r\n)\r\n)*0\r\n\r\n\r\nor \nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\nmax_over_time(kube_deployment_created{namespace=~\"$namespace\"}[$__range])\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)* 0-1"
    },
    {
     "expr": "\nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(last_over_time(kube_deployment_spec_replicas{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}[$__range])\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n) "
    },
    {
     "expr": "max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\nkube_deployment_created{namespace=~\"$namespace\"}\n*\non(deployment) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n)\n) * 1\nor \nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\nmax_over_time(kube_deployment_created{namespace=~\"$namespace\"}[$__range])\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)* 0"
    },
    {
     "expr": "max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(last_over_time(\nkube_deployment_created{namespace=~\"$namespace\"}[$__range]\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n) )* 1000",
     "legendFormat": "start_time"
    },
    {
     "expr": "max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(last_over_time(\ntimestamp(kube_deployment_created{namespace=~\"$namespace\"})[$__range:30s]\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n) )* 1000 ",
     "legendFormat": "end_time"
    },
    {
     "expr": "max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(min_over_time(\nkube_deployment_created{namespace=~\"$namespace\"}[$__range]\n)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n) )* 1000"
    },
    {
     "expr": "\nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(\n(((kube_deployment_status_replicas_available{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}) == (kube_deployment_status_replicas{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}))*0+1)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n  )\n)\n)\nor\nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(\n(((kube_deployment_status_replicas_unavailable{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}) == (kube_deployment_status_replicas{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}))*0-1)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n  )\n)\n) \nor\nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) \n(\n(((kube_deployment_status_replicas_unavailable{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"} < kube_deployment_status_replicas{ app_kubernetes_io_instance=\"\", namespace=~\"$namespace\"}))*0)\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n\n(\n  max by (deployment, namespace, label_operation_aipub_ten1010_io_owner) (\n    kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}\n  )\n)\n) \nor\nmax by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\nmax_over_time(kube_deployment_created{namespace=~\"$namespace\"}[$__range])\n*\non(deployment, namespace) group_left(label_operation_aipub_ten1010_io_owner)\n(\n  max by (label_operation_aipub_ten1010_io_owner, namespace, deployment) (\n  max_over_time(kube_deployment_labels{label_operation_aipub_ten1010_io_owner!=\"\"}[$__range])\n  )\n)\n)* 0+2"
    }
   ]
  },
  {
   "title": "응답 시간(백분위수)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P9999"
    }
   ]
  },
  {
   "title": "평균 응답 시간(네임스페이스)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace) (((\r\nsum by (pod, deployment, namespace) (increase(response_latency_ms_sum{namespace=~\"$namespace\", direction=\"inbound\", target_port!=\"4191\"}[1m]))\r\n\r\n)\r\n/\r\n(\nsum by (pod, deployment, namespace) (increase(response_latency_ms_count{namespace=~\"$namespace\", direction=\"inbound\", target_port!=\"4191\"}[1m]))\n))\n\r\r\n* on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\n\n\r\n  kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n\r))\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "응답 상태",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (\r\n  response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", node=\"\", namespace=~\"$namespace\", namespace!=\"\", le=\"+Inf\"} -   (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", node=\"\", namespace=~\"$namespace\", namespace!=\"\", le=\"+Inf\"} offset 30s)\r\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "응답 실패 건수(네임스페이스)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", le=\"+Inf\", status_code=~\"4.*|5.*\",  namespace!=\"\", namespace=~\"$namespace\"}))\n\r\n\r\n\r\n- (sum by (namespace) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", le=\"+Inf\", status_code=~\"4.*|5.*\", namespace!=\"\", namespace=~\"$namespace\"} offset 30s))",
     "legendFormat": "{{namespace}}"
    },
    { "legendFormat": "{{namespace}}" }
   ]
  },
  { "title": "요청 -  네임스페이스", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "요청 분배 비율 (네임스페이스)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(request_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    request_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[$__range])\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "초 당 요청수(네임스페이스)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=~\"$namespace\", namespace!=\"\"}[1m]))\r\n\r\n\r\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "요청건수 (네임스페이스)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation, namespace) (request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace!=\"\", namespace=~\"$namespace\"})\r\n\r\n\r\n- sum by (operation, namespace) (request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace!=\"\", namespace=~\"$namespace\"} offset 30s)\r\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "요청 - 노드", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "요청 분배 비율 (네임스페이스)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(request_operation_total{namespace=\"\", operation=\"\", pod=\"\", node!=\"\"}[$__range]) -   \n(\r\n    request_operation_total{namespace=\"\", operation=\"\", pod=\"\", node!=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(request_operation_total{namespace=\"\", operation=\"\", pod=\"\", node!=\"\"}[$__range])\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "초 당 요청수(노드)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=\"\", node!=\"\"}[1m]))\r\n\r\n\r",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "요청건수 (노드)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=\"\", node!=\"\"} or kube_node_created{}*0)\r\n\r\n\r\n- sum by (node) (request_operation_total{pod=\"\", deployment=\"\", operation=\"\", namespace=\"\", node!=\"\"} offset 30s or kube_node_created{}*0)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "응답 시간", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "응답시간 분포",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=\"$namespace\",  operation=\"\", le=\"1\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1\", pod=\"\", node=\"\"}[$__range])\n)\n)\n",
     "legendFormat": "<1ms"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "1-5ms"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "5-10ms"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "10-50ms"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"100\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"100\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"100\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "50-0.1s"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"500\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"500\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"500\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"100\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"100\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"100\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "0.1s--0.5s"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"500\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"500\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"500\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "0.5s-1s"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"1000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "1-5s"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"5000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "5-10s"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50000\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"10000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "10-50s"
    },
    {
     "expr": "sum (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"+Inf\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"+Inf\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"+Inf\", pod=\"\", node=\"\"}[$__range])\n)\n)-\nsum by (operation) (\nmax_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50000\", pod=\"\", node=\"\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50000\", pod=\"\", node=\"\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", le=\"50000\", pod=\"\", node=\"\"}[$__range])\n)\n)",
     "legendFormat": "50s-Inf"
    }
   ]
  },
  {
   "title": "응답 시간(백분위수)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9999,\r\n  sum by (le) (\r\n    (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"} offset 30s\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\"}[30s])\n))  \r\n  )\r\n)\n\n\r\r",
     "legendFormat": "P9999"
    }
   ]
  },
  {
   "title": "평균 응답 시간(네임스페이스)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace) (((\r\nsum by (pod, deployment, namespace) (increase(response_latency_ms_sum{namespace=~\"$namespace\", direction=\"inbound\", target_port!=\"4191\"}[1m]))\r\n\r\n)\r\n/\r\n(\nsum by (pod, deployment, namespace) (increase(response_latency_ms_count{namespace=~\"$namespace\", direction=\"inbound\", target_port!=\"4191\"}[1m]))\n))\n\r\r\n* on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\n\n\r\n  kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\", job!=\"kubernetes-service-endpoints\"}\r\n\r))\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "평균 응답 시간(노드)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node) (((\r\nsum by (pod, namespace) (increase(response_latency_ms_sum{namespace=~\"$namespace\", direction=\"inbound\", target_port!=\"4191\"}[1m]))\r\n\r\n)\r\n/\r\n(\nsum by (pod, namespace) (increase(response_latency_ms_count{namespace=~\"$namespace\", direction=\"inbound\", target_port!=\"4191\"}[1m]))\n))\n\r\r\n* on(pod, namespace) group_left(label_operation_aipub_ten1010_io_owner)\r\n(\n\r\n  kube_pod_labels{label_operation_aipub_ten1010_io_owner!=\"\", namespace=~\"$namespace\", job!=\"kubernetes-service-endpoints\"}\n \r\n\r\n)\n* on(pod, namespace) group_left(node)\r\n(\n  sum by (pod, namespace, node)(\n\r\n    kube_pod_info{node!=\"\", job!=\"kubernetes-service-endpoints\"}\n\r\n   )\n))\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "응답 상태", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "응답 코드 비율",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, status_code) (max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\", le=\"+Inf\"}[$__range]) -   \n(\r\n    response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\", le=\"+Inf\"} offset $__range\r\n    or\r\n    0 * max_over_time(response_latency_ms_bucket_operation_total{namespace=~\"$namespace\", namespace!=\"\", operation=\"\", pod=\"\", node=\"\", le=\"+Inf\"}[$__range])\n)) \n",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "응답 상태",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\nsum by (status_code) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", node=\"\", namespace=~\"$namespace\", namespace!=\"\", le=\"+Inf\"} - (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", node=\"\", namespace=~\"$namespace\", namespace!=\"\", le=\"+Inf\"} offset 30s))\r\n",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "응답 실패 건수(네임스페이스)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", le=\"+Inf\", status_code=~\"4.*|5.*\",  namespace!=\"\", namespace=~\"$namespace\"}))\n\r\n\r\n\r\n- (sum by (namespace) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", le=\"+Inf\", status_code=~\"4.*|5.*\", namespace!=\"\", namespace=~\"$namespace\"} offset 30s))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "응답 실패 건수(노드)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", le=\"+Inf\", status_code=~\"4.*|5.*\",  node!=\"\", namespace=\"\"}))\n\r\n\r\n\r\n- (sum by (node) (response_latency_ms_bucket_operation_total{pod=\"\", deployment=\"\", operation=\"\", le=\"+Inf\", status_code=~\"4.*|5.*\", node!=\"\", namespace=\"\"} offset 30s))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}