{
 "title": "Ten Job Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(kube_job_info{namespace=\"$namespace\"}, job_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_info{namespace=\"$namespace\", job_name=\"$job_name\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_info{namespace=\"$namespace\", job_name=\"$job_name\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Owner Resource",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_owner{namespace=\"$namespace\", job_name=\"$job_name\", owner_name!=\"\"}",
     "legendFormat": "{{owner_kind}} / {{owner_name}}"
    }
   ]
  },
  {
   "title": "COMPLETE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (kube_job_complete{namespace=\"$namespace\", job_name=\"$job_name\", condition=\"true\"} * 1)\n  or (kube_job_complete{namespace=\"$namespace\", job_name=\"$job_name\", condition=\"false\"} * 0)\n  or (kube_job_complete{namespace=\"$namespace\", job_name=\"$job_name\", condition=\"unknown\"} * -1)\n  or vector(0)\n)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "COMPLETIONS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_status_succeeded{namespace=\"$namespace\", job_name=\"$job_name\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "kube_job_spec_completions{namespace=\"$namespace\", job_name=\"$job_name\"}",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_status_completion_time{namespace=\"$namespace\", job_name=\"$job_name\"} - \nkube_job_status_start_time{namespace=\"$namespace\", job_name=\"$job_name\"}\nor\ntime() - kube_job_status_start_time{namespace=\"$namespace\", job_name=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_job_created{namespace=\"$namespace\", job_name=~\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Owned Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Job 할당 GPU / MIG 인스턴스",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n    )\n    * on (exported_namespace, exported_pod) group_left(owner_name)\n    label_replace(\n      label_replace(\n        kube_pod_owner{\n          namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n        }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)"
    }
   ]
  },
  { "title": "시스템", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (namespacem, pod, owned_name) (\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$job_name.*\", container!=\"\", image!=\"\"}[5m])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$job_name.*\", container!=\"\", image!=\"\"}\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:gpu_temp\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "description": "GPU  전력 소모량",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:power\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:power\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:util\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n    )\n    * on (exported_namespace, exported_pod) group_left(owner_name)\n    label_replace(\n      label_replace(\n        kube_pod_owner{\n          namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n        }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, node, GPU_I_ID) (\n  gpu:resource:util\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container, node)\n  label_replace(\n    sgn(\n      MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n    )\n    * on (exported_namespace, exported_pod) group_left(owner_name)\n    label_replace(\n      label_replace(\n        kube_pod_owner{\n          namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n        }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n    ), \"node\", \"$1\", \"Hostname\", \"(.+)\"\n  )\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "SM Active",
   "type": "graph",
   "description": "연산 자원의 공간 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:sm_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:sm_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "description": "GPU의 연산자원 중 텐서코어의 활용도",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:tensor_core\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:tensor_core\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory R/W Utilization",
   "type": "graph",
   "description": "GPU 메모리의 읽고 쓰기 시간을 합한 시간의 비율 \n(GPU Memory bandwidth)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:dram_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    GPU_POD_UTIL_LIMIT{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)\nor\nsum by (exported_pod, modelName, gpu, GPU_I_PROFILE, GPU_I_ID) (\n  gpu:resource:dram_active\n  * on(UUID, GPU_I_ID)\n  group_left(exported_pod, exported_namespace, exported_container)\n  sgn(\n    MIG_POD_ALLOCATED{exported_namespace=\"$namespace\", exported_pod=~\"$job_name.*\"}\n  )\n  * on (exported_namespace, exported_pod) group_left(owner_name)\n  label_replace(\n    label_replace(\n      kube_pod_owner{\n        namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n      }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n    ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n  )\n)",
     "legendFormat": "Pod: {{exported_pod}} / GPU: {{modelName}}({{gpu}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU 메모리 활용 크기",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_pod, UUID, gpu, modelName, GPU_I_PROFILE) (\n  GPU_POD_MEMORY{\n    exported_namespace=\"$namespace\",\n    exported_pod=~\"$job_name.*\"\n  }\n  * on(exported_namespace, exported_pod, UUID) group_left(GPU_I_PROFILE)\n  (\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$job_name.*\"\n      }\n    )\n    * on (exported_namespace, exported_pod) group_left(owner_name)\n    label_replace(\n      label_replace(\n        kube_pod_owner{\n          namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n        }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n    )\n    unless\n    label_replace(\n      sgn(\n        MIG_POD_ALLOCATED{\n          exported_namespace=\"$namespace\",\n          exported_pod=~\"$job_name.*\"\n        }\n      )\n      * on (exported_namespace, exported_pod) group_left(owner_name)\n      label_replace(\n        label_replace(\n          kube_pod_owner{\n            namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n          }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n        ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n      )\n      ,\n      \"UUID\", \"$1\", \"MIG_UUID\", \"(.+)\"\n    )\n    * on (exported_namespace, exported_pod, UUID) group_left()\n    sgn(\n      GPU_POD_UTIL_LIMIT{\n        exported_namespace=\"$namespace\",\n        exported_pod=~\"$job_name.*\"\n      }\n    )\n    * on (exported_namespace, exported_pod) group_left(owner_name)\n    label_replace(\n      label_replace(\n        kube_pod_owner{\n          namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"\n        }, \"exported_namespace\", \"$1\", \"namespace\", \"(.+)\"\n      ), \"exported_pod\", \"$1\", \"pod\", \"(.+)\"\n    )\n  )\n)",
     "legendFormat": "{{exported_pod}}-{{modelName}}--({{gpu}})({{gpu_2}})-{{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Network Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$job_name.*\"}[$__rate_interval])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$job_name.*\"}[$__rate_interval])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(\n  sum by (pod) (\n    rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$job_name.*\"}[5m])\n    * on (namespace, pod) group_left(owner_name)\n    kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n\r\r\r\r\r  )\n\r\r\r\r\r\r\r)",
     "legendFormat": "(Reads) Pod: {{pod}}"
    },
    {
     "expr": "ceil(\n  sum by (pod) (\n    rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$job_name.*\"}[5m])\n    * on (namespace, pod) group_left(owner_name)\n    kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n  )\n)",
     "legendFormat": "(Writes) Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$job_name.*\", container!=\"\"}[5m])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "(Reads) Pod: {{pod}}"
    },
    {
     "expr": "sum by (pod) (\n  rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$job_name.*\", container!=\"\"}[5m])\n  * on (namespace, pod) group_left(owner_name)\n  kube_pod_owner{namespace=\"$namespace\", owner_kind=\"Job\", owner_name=\"$job_name\"}\n)",
     "legendFormat": "(Writes) Pod: {{pod}}"
    }
   ]
  }
 ]
}