---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace:  {{ include "efkNamespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
  namespace:  {{ include "efkNamespace" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["create", "get", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
  namespace:  {{ include "efkNamespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa
  namespace:  {{ include "efkNamespace" . }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io