apiVersion: v1
appVersion: 8.15.3
description: Elasticsearch with Nori tokenizer (pre-installed)
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/elasticsearch.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: elasticsearch
sources:
- https://github.com/elastic/elasticsearch
version: 8.15.3
dependencies:
  - name: elasticsearch
    version: 8.15.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled