replicaCount: 1

image:
  repository: "" # ## HELM installer ##
  pullPolicy: Always
  tag: "" # ## HELM installer ##

imagePullSecrets:
  - name: harbor-java
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations:
  ad.datadoghq.com/aipub-backend-gateway.logs: '[{"source": "java", "service": "aipub-backend-gateway"}]'
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 8080

resources: { }

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - hostPath:
      path: /opt/aipub/certs
      type: Directory
    name: ca-certs

volumeMounts:
  - mountPath: /certificates
    name: ca-certs
    readOnly: true

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  grpc:
    client:
      backendApi:
        address: dns:///aipub-backend-api.aipub.svc.cluster.local:9090
      backendUsage:
        address: dns:///aipub-backend-usage.aipub.svc.cluster.local:9090
  spring:
    profiles:
      active: production
    web:
      resources:
        addMappings: "false"
  app:
    jwt:
      secretKey: "" # ## HELM installer ##
    application:
      type: BACKEND_GATEWAY
      id: backend-gateway
    cookie:
      domain: "" # ## HELM installer ##
    web:
      k8sProxy:
        k8sUri: https://10.96.0.1
      security:
        allowedOrigins_0: "" # ## HELM installer ##
        allowedOrigin: "" # ## HELM installer ##
        basicAuth:
          user:
            username: "testuser"
            password: "asdasdasd"
            role: "aipub-admin"
  logging:
    level:
      orgSpringframeworkWeb: "" # ## HELM installer ##
