replicaCount: 1

image:
  repository: vnode2.pnode1.idc1.ten1010.io:8443/aipub-ops-4.1.0/lgd-backend-welcome
  pullPolicy: IfNotPresent
  tag: "1.0.4"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: "lgd-backend-welcome"

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "lb1"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  hosts:
    - host: welcome.lgdisplay.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: lgd-backend-welcome-tls
      hosts:
        - welcome.lgdisplay.com

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: ca-certs
    hostPath:
      path: /opt/aipub/certs
      type: Directory

volumeMounts:
  - mountPath: /etc/ssl/certs
    name: ca-certs
    readOnly: true

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  server:
    port: 8080
  spring:
    profiles:
      active: "production"
  app:
    gateway:
      ssoUrl: "https://aip.lgdisplay.com"
      backendUrl: "https://aip.lgdisplay.com"
