apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ if .Files.Get "tls.crt" }}{{ .Files.Get "tls.crt" | b64enc }}{{ else }}{{ .Values.tlsCrt | b64enc }}{{ end }}
  tls.key: {{ if .Files.Get "tls.key" }}{{ .Files.Get "tls.key" | b64enc }}{{ else }}{{ .Values.tlsKey | b64enc }}{{ end }}