replicaCount: 1

image:
  repository: aipub-web
  pullPolicy: IfNotPresent
  tag: "beta-2.0.15"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  aipubVersion: "v4.0.0"
  aipubTitle: "AI Pub"
  aipubApiUrl: https://aipub.cluster7.idc1.ten1010.io
  aipubBaseHost: cluster7.idc1.ten1010.io
  aipubLogoutRedirectUrl: https://aipub.cluster7.idc1.ten1010.io/welcome
  aipubBrand: "aipub"
  aipubUseMock: "false"
  aipubDocsUrl: https://aipub.cluster7.idc1.ten1010.io/docs
  aipubHarborUrl: https://aipub-harbor.cluster7.idc1.ten1010.io
  aipubMode: ops
  aipubUseSso: "false"
  aipubNodeUrl: https://aipub.cluster7.idc1.ten1010.io/alloc
  aipubNoticeUrl: https://aipub.cluster7.idc1.ten1010.io/notice
  aipubReportUrl: https://aipub.cluster7.idc1.ten1010.io/report
  aipubKibanaUrl: https://aipub.cluster7.idc1.ten1010.io/kibana
  aipubStreamlitUrl: https://aipub.cluster7.idc1.ten1010.io/streamlit
  aipubSshPortMin: "1024"
  aipubSshPortMax: "65535"
  aipubVolumes: '[{"type":"nfs","value":"nfs"},{"type":"storageclass","value":"ontap-nas"}]'
  appPrefix: AIPUB_
  assetDir: /usr/share/nginx/html
