replicaCount: 1

image:
  repository: ghcr.io/ten1010-io/aipub-backend-usage
  pullPolicy: Always
  tag: "4.0.0"

imagePullSecrets:
  - name: ghcr-ten1010
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: 9090

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - hostPath:
      path: /opt/aipub/certs
      type: Directory
    name: ca-certs

volumeMounts:
  - mountPath: /etc/ssl/certs
    name: ca-certs
    readOnly: true

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  spring:
    profiles:
      active: production
    dataSource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://keycloak-postgresql.aipub.svc.cluster.local:5432/usages
      username: aipub
      password: Password1@
    jpa:
      hibernate:
        ddlAuto: none
      showSql: false
      generateDdl: false
      openInView: false
    grpc:
      server:
        port: 9090
        reflection:
          enabled: true
  app:
    jwt:
      secretKey: n0dCUStAujBwdQl1rbn80FQWNnBx03l6
    application:
      type: BACKEND_USAGE
      id: backend_usage
    k8s:
      verifyingSsl: false
      kubeConfig:
        mode: in_cluster
