apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aipub-crd-exporter.fullname" . }}
  labels:
    {{- include "aipub-crd-exporter.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "aipub-crd-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aipub-crd-exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
