apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aipub-crd-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aipub-crd-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aipub-crd-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aipub-crd-exporter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aipub-crd-exporter.serviceAccountName" . }}
      containers:
      - name: {{ include "aipub-crd-exporter.fullname" . }}
        image: {{ include "aipub-crd-exporter.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-metrics
          containerPort: {{ .Values.service.targetPort }}
        env:
        - name: EXPORTER_PORT
          value: "{{ .Values.service.targetPort }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
