
prometheus:
  url: http://promstack-kube-prometheus-prometheus.prometheus.svc

image:
  pullPolicy: Never

nodeSelector:
  kubernetes.io/hostname: vnode1.pnode7.idc1.ten1010.io

rules:
  default: false
  custom:
    - seriesQuery: 'request_total{direction = "inbound"}'
      resources:
        template: "<<.Resource>>"
      name:
        as: "rps"
      metricsQuery: |
        sum(rate(<<.Series>>{<<.LabelMatchers>>, target_port != "4191"}[1m])) by (<<.GroupBy>>) / sum(kube_deployment_status_replicas_available{<<.LabelMatchers>>}) by (<<.GroupBy>>)