pipeline {
    agent any

    environment {
        REPO = "git@github.com:ten1010-io/aipub-ten-cluster-CD.git"
        BRANCH = "main"
        REMOTE_SERVER = "cluster7"
    }

    stages {
        stage('Clone Repo') {
            steps {
                sh '''
                rm -rf repo
                git clone $REPO repo
                '''
            }
        }

        stage('Modify & Push') {
            steps {
                sh '''
                cd repo
                git pull origin $BRANCH
                mkdir -p infra
                echo "test git $(date)" > infra/test.txt
                
                git config user.email "jenkins@local"
                git config user.name "jenkins"
                git add infra/test.txt
                git commit -m "test: update test.txt from jenkins" || echo "no changes"
                git push origin $BRANCH
                '''
            }
        }

        stage('Remote Kubectl Check') {
            steps {
                // 이미 키가 등록되어 있으므로 직접 ssh 호출
                sh """
                echo "cluster 1"
                ssh -o StrictHostKeyChecking=no jenkins@cluster1 "sudo kubectl get po -n aipub"

                echo "cluster 4"
                ssh -o StrictHostKeyChecking=no jenkins@cluster4 "sudo kubectl get po -n aipub"

                echo "cluster 6"
                ssh -o StrictHostKeyChecking=no jenkins@cluster6 "sudo kubectl get po -n aipub"

                echo "cluster 7"
                ssh -o StrictHostKeyChecking=no jenkins@cluster7 "sudo kubectl get po -n aipub"

                echo "cluster 8"
                ssh -o StrictHostKeyChecking=no jenkins@cluster8 "sudo kubectl get po -n aipub"

                echo "cluster 9"
                ssh -o StrictHostKeyChecking=no jenkins@cluster9 "sudo kubectl get po -n aipub"

                echo "cluster 10"
                ssh -o StrictHostKeyChecking=no jenkins@cluster10 "sudo kubectl get po -n aipub"

                echo "cluster 11"
                ssh -o StrictHostKeyChecking=no jenkins@cluster11 "sudo kubectl get po -n aipub"
                
                """
            }
        }
    }

    post {
        success { echo '🎉 모든 작업 완료!' }
        failure { echo '❌ SSH 연결 실패 - 키 마운트 여부 확인 필요' }
    }
}
