apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: app
          image: "{{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args: ["python3 main.py"]
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DURATION
              value: "{{ .Values.app.duration }}"
            - name: SERVICE_PORT
              value: "{{ .Values.service.port }}"
            - name: MIG_SUPPORTED_GPUS_CONFIG_MAP
              value: "{{ .Values.configMap.name }}"
            - name: NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: "all"
