git_clone_init_container: false
git_user_name: ""
git_token: ""
promstack_release: promstack
git_branch: ""
metric_export_mode: "PUSHGATEWAY"
pushgateway_uri: "http://pushgateway-prometheus-pushgateway.promstack.svc:9091"
prometheus_uri: "http://promstack-ops-kube-prometh-prometheus.promstack.svc:9090"
scrape_interval: 30

image:
  repository: "persistent-linkerd-exporter"
  tag: "1.0.0"
  imagePullPolicy: "Never"
  
podMonitor:
  additionalLabels: {}
resources: {}
  # requests:
  #   cpu: 200m
  #   memory: 250Mi
  # limits:
  #   cpu: 200m
  #   memory: 250Mi  

namespaceOverride: ""

affinity: {}

nodeSelector: {}
#  node-role.kubernetes.io/control-plane: ""
#
tolerations: []
#  - key: "node-role.kubernetes.io/control-plane"
#    effect: "NoSchedule"
#    operator: "Exists"