apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cert-pod
  namespace: aipub
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep infinity
      image: ubuntu:22.04-util
      imagePullPolicy: IfNotPresent
      name: ubuntu-container
      resources: {}
      volumeMounts:
        - mountPath: /usr/local/share/ca-certificates
          name: cert-volume
  nodeName: vnode5.pnode6.idc1.ten1010.io
  volumes:
    - hostPath:
        path: /opt/aipub/certs
        type: Directory
      name: cert-volume