apiVersion: v1
kind: Service
metadata:
  name: "aipub-welcome"
  labels:
    {{- include "aipub-welcome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aipub-welcome.selectorLabels" . | nindent 4 }}
