replicaCount: 1

image:
  repository: ghcr.io/ten1010-io/aipub-sso-gateway
  pullPolicy: IfNotPresent
  tag: "4.0.0"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: "aipub-sso-gateway"

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "lb1"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  hosts:
    - host: aipub.cluster5.idc1.ten1010.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: aipub-tls
      hosts:
        - aipub.cluster5.idc1.ten1010.io

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - hostPath:
      path: /opt/aipub/certs
      type: Directory
    name: ca-certs
  - name: java-agents
    hostPath:
      path: /opt/aipub/agents
      type: Directory

volumeMounts:
  - mountPath: /certificates
    name: ca-certs
    readOnly: true
  - mountPath: /opt/aipub/agents
    name: java-agents

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  server:
    port: 8080
  spring:
    profiles:
      active: "production"
    cloud:
      gateway:
        server:
          webflux:
            userCreate:
              id: "user_create"
              uri: "no://op"
              predicatePath: "Path=/api/v1alpha1/users"
              predicateMethod: "Method=POST"
              filterName: "AipubUserAdapter"
            userUpdatePassword:
              id: "user_update_password"
              uri: "no://op"
              predicatePath: "Path=/api/v1alpha1/users/*/password"
              predicateMethod: "Method=PATCH"
              filterName: "AipubUserAdapter"
            userResetPassword:
              id: "user_reset_password"
              uri: "no://op"
              predicatePath: "Path=/api/v1alpha1/users/*/resetpassword"
              predicateMethod: "Method=PUT"
              filterName: "AipubUserAdapter"
            aipubBackend:
              id: "backend_gateway"
              uri: "http://aipub-backend-gateway.aipub.svc.cluster.local:8080"
              predicates:
                path: "Path=/api/**"
              filters:
                aipubAdapter:
                  name: "WelcomeAdapter"
            aipubFrontend:
              id: "aipub_frontend"
              uri: "http://aipub-frontend.aipub.svc.cluster.local"
              predicates:
                path: "Path=/**"
              filters:
                aipubAdapter:
                  name: "WelcomeAdapter"
            kibana:
              id: "kibana"
              predicates:
                path: "Path=/kibana/**"
              uri: "https://kibana-kibana.aipub-efk.svc.cluster.local:5601"
              filters:
                basicAuthAdapter:
                  name: "BasicAuthAdapter"
                  args:
                    adminUser: "elastic"
                    adminPassword: "n77C28hfcMVMbXVI"
                    userUser: aipub
                    userPassword: "aipub1@"
                removeRequestHeader:
                  name: "RemoveRequestHeader"
                  args:
                    name: "Cookie"
            streamlit:
              id: "streamlit_main"
              uri: "http://aipub-monitoring.aipub.svc.cluster.local:8501"
              predicates:
                path: "Path=/streamlit/**"
              filters:
                name: "BearerAuthAdapter"
            notice:
              id: "notice_main"
              uri: "http://aipub-notice-board-api.aipub-efk.svc.cluster.local:8009"
              predicates:
                path: "Path=/notice/**"
              filters:
                arg: "StripPrefix=1"
            alloc:
              id: "alloc_main"
              uri: "http://aipub-cluster-overview-api.aipub-promstack.svc.cluster.local:8008"
              predicates:
                path: "Path=/alloc/**"
              filters:
                arg: "StripPrefix=1"
            report:
              id: "report_main"
              uri: "http://aipub-report.aipub.svc.cluster.local:8000"
              predicates:
                path: "Path=/report/**"
              filters:
                arg: "StripPrefix=1"
            httpclient:
              ssl:
                useInsecureTrustManager: true
              compression: true
              websocketMaxFramePayloadLength: "25165824"  # 24 * 1024 * 1024 24MB
  app:
    domain:
      auth:
        backendServerUrl: http://aipub-backend-gateway.aipub.svc.cluster.local:8080
        basicAuthUsername: testuser
        basicAuthPassword: asdasdasd
        verifyingSsl: false
        initPassword: Ten1010!!
      keycloak:
        serverUrl: https://aipub-keycloak.cluster5.idc1.ten1010.io
        clientRealm: aipub
        clientId: k8s
        clientSecret: uyutK2O210wRjs1GOJRKEEAHhD2lNbP5
        verifyingSsl: false
        keycloakPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArwgK+fKmhi/hISvh14dNIGMQQVg9Jh5SUx1Pix3SdeYjy+melF1z5ZYbHa/CUoQBj3uwAr7k5x+Is9ZdCA3u1N5jP9E0UPxdGkRdDcJMp0ZLFUM355Zhkrl0IiAs/4Xz8QTIXm1wbQj+1mP7kPDezAHGxVmtltM59icmtrAL4U1dhOxaGcVPlVVFOLqDzmao79yIwu2b5ckF8pwWjL0tpJIDgTJF4Ei0y7+Yba+FMja4xUtSOfGUmLyYaos9WKQWScmKCsEknboQ9SjLZz1oWN5yKzGO9LRUS2FZotGZW9o/1kWzumhDn4i6y2uK93gEQn7cJquy658kTQQx45PDXQIDAQAB
    cookie:
      accessMaxAge: "1800"
      refreshMaxAge: "2592000"
      idMaxAge: "1800"
      domain: ".cluster5.idc1.ten1010.io"
    redirect:
      indexUrl: "https://aipub.cluster5.idc1.ten1010.io/welcome/index"
      aipubUrl: "https://aipub.cluster5.idc1.ten1010.io"
  web:
    client:
      maxInMemorySize: "20971520"   # 20MB
  cors:
    allowedOrigin: "https://aipub.cluster5.idc1.ten1010.io"

agent:
  javaToolOptions: "-javaagent:/opt/aipub/agents/dd-java-agent.jar"
  ddTraceAgentPort: "8126"
  ddService: "aipub-sso-gateway"
  ddEnv: "production"
  ddVersion: "1.0.0"
  host: "aipub-backend-datadog.aipub.svc.cluster.local"
  ddProfilingEnabled: "true"
  ddProfilingAllocationEnabled: "true"
