
tlsVerify: false
kibanaHost: https://101.202.62.74:30561/
elasticCredentialSecretName: elasticsearch-master-credentials
kibanaDashboardConfigmapName: kibana-dashboard-ids
k8sConfigPath: dev_config
resources: {}
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
image:
  repository: kibana-postinstall-job
  tag: "1.0.0"
  imagePullPolicy: Never

affinity: {}

nodeSelector: {}
#  kubernetes.io/hostname: vnode1.pnode7.idc1.ten1010.io
tolerations: []
#  - key: "node-role.kubernetes.io/control-plane"
#    effect: "NoSchedule"
#    operator: "Exists"