replicaCount: 1

image:
  repository: ghcr.io/ten1010-io/aipub-backend-api
  pullPolicy: IfNotPresent
  tag: "1.0.4"

imagePullSecrets:
  - name: ghcr-ten1010
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: 9090

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 2Gi

livenessProbe:
  tcpSocket:
    port: grpc
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: grpc
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

#volumes:
#  - hostPath:
#      path: /opt/aipub/certs
#      type: Directory
#    name: ca-certs
#
#volumeMounts:
#  - mountPath: /etc/ssl/certs
#    name: ca-certs
#    readOnly: true

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  spring:
    profiles:
      active: production
    batch:
      jdbc:
        initializeSchema: never
    dataSource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://keycloak-postgresql.aipub.svc.cluster.local:5432/aipub
      username: aipub
      password: Password1@
      hikari:
        maximumPoolSize: "10"
    jpa:
      hibernate:
        ddlAuto: validate
      showSql: false
      generateDdl: false
      openInView: false
    grpc:
      server:
        port: 9090
        reflection:
          enabled: true
    flyway:
      enabled: true
      baselineOnMigration: true
  app:
    jwt:
      secretKey: qcMrVXXbKmxvAUz4r7c505YUk6sThCUR
    application:
      type: BACKEND_API
      id: backend_api
    domain:
      auth:
        initPassword: Ten1010!!
      keycloak:
        serverUrl: https://aipub-keycloak.example.com
        issuerUrl: https://aipub-keycloak.example.com/realms/aipub
        tokenUrl: https://aipub-keycloak.example.com/realms/aipub/protocol/openid-connect/token
        clientRealm: aipub
        clientId: k8s
        clientSecret: qcMrVXXbKmxvAUz4r7c505YUk6sThCUR
        userRealm: aipub
        userRealmPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzq7i3Q1Mk+wyAhiTLpLhFRPVneZdnWzkJWfYdO3DjXjoLYNrRTBcEFiof0A0+sGe+ZLcqZrJUlfcM3PYiCcQ2blTg0nkCxDzOfHoNjHVN3ZzpFeKi3TnlhkaXIett2P6oQBXhS4fKyMFdwWkGWt5scTV/h8dhryiLtiG3iUGqqE55ETohK28Sb+MJC0WF7GIWZDauvSl2JPP9703RCuJX47TcskgwpO/gzRtulWz72DV/moJmRxVGCmfrHyrAbw/4Ol6ZVfVI7Rcq3rRtxAY66nJKI+sVkLlU4y6YC7C8knImGWYQx1MMh9/LNnomNrPPrdWAI+NLlbDW5j+jsRfrwIDAQAB
        verifyingSsl: false
      harbor:
        serverUrl: https://aipub-harbor.example.com
        verifyingSsl: false
        username: admin
        password: Harbor12345
      k8sProxy:
        k8sUri: https://10.96.0.1
        k8sManagerToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Il9GMXdESnFkVkptZkt4YWxjQVZPQnl1WEV4Q0FUMks1bk4wSWJRSDVNbnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhaXB1YiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhaXB1Yi1yZXNvdXJjZXMtbWFuYWdlci1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYWlwdWItcmVzb3VyY2VzLW1hbmFnZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJjYWMxNmQ0NS04MzFmLTQ2NjQtYTZmOC0wMGZkNDE2Mjg0YzgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YWlwdWI6YWlwdWItcmVzb3VyY2VzLW1hbmFnZXIifQ.ZroZkCh-U5PEC2xAWUiEeWm9fx9VMvuMXn42cI41oJvWUe7-aoPoienzV7_a-2wKW7J1TIgxLrSVPofTTxLPr1TE3jMNfLLfuWawjmkAyyG6Z6f8lku1LzTMHrDqg-UTnGTR5aCiehPy9p1_l5gtgnwByn4DgkEwy64dyY8GbBQP_b7tGUO0kuNV0CYcgYXvVF8kBKNApuLKVcuxUb6h8AZb47C0YO13QiGVrlc9uj7fn332xu8e4QSntAnpL7vgN0j14YhUKiUS3XFhb39vuFAN9m6QC239KT90Rjmlj_8b34boWhBCNPgjBfNsNYc4XM7oS23MPTiC5EKdO5FjGw
        verifyingSsl: false
    esClient:
      serverUrl: http://elasticsearch-master.aipub-efk:9200
      username: elastic
      password: ## LGE ##
      verifyingSsl: false
    simplejavamail:
      smtpHost: email-smtp.ap-northeast-2.amazonaws.com
      smtpPort: 465
      smtpUsername: AKIAQRYAI5QYE6L6OUOW
      smtpPassword: BAoxnYj9qLmRkhEhSnPbAc6YDGoDfpSYb7IztimMhXig
      fromAddress: helloten@ten1010.io
      templateHomeUrl: https://aipub.example.com/
      tlsEnabled: true
      sendEnable: false
    soapMms:
      requestNamespace: http://xmlns.oracle.com/pcbpel/adapter/db/IKEP/INSERT_MMS/
      mmsUrl: http://eaiws.lgdisplay.com:3000/orabpel/LGD_COMMON/callMmsEP/1.0
      callback: "1544-3999"
      sendEnable: false
  resilience4j:
    retry:
      instances:
        emailRetry:
          maxAttempts: 3
          waitDuration: 5s
          retryExceptions: java.io.IOException
        emailAllRetry:
          maxAttempts: 3
          waitDuration: 5s
          retryExceptions: java.io.IOException
