replicaCount: 1

image:
  repository: ghcr.io/ten1010-io/aipub-backend-gateway
  pullPolicy: Always
  tag: "4.0.0"

imagePullSecrets:
  - name: ghcr-ten1010
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: { }

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - hostPath:
      path: /opt/aipub/certs
      type: Directory
    name: ca-certs

volumeMounts:
  - mountPath: /etc/ssl/certs
    name: ca-certs
    readOnly: true

nodeSelector: { }

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

envFrom:
  configMapSuffix: envs
  secretSuffix: envs

applicationYaml:
  grpc:
    client:
      backendApi:
        address: dns:///aipub-backend-api.aipub.svc.cluster.local:9090
      backendUsage:
        address: dns:///aipub-backend-usage.aipub.svc.cluster.local:9090
  spring:
    profiles:
      active: production
    web:
      resources:
        addMappings: "false"
  app:
    jwt:
      secretKey: n0dCUStAujBwdQl1rbn80FQWNnBx03l6
      keycloakPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxrcP3IIHWgYe5svKq9IpiRY0RK+Xlwiw5t+UsopgS7/vbFb/CLRtXmmLZTPtdwJx050c5p/4mXBHXpstX01cGZtZq8lm3m3+rhTewGHXIbYKGwJcCxEmRzqNEEMVxICp9QZC88VS3rrTj6OjwtF4T8wFnuyifY2zkCvOa4NbykADkYrrxbevGr/BEWIbQsUtkpzZMYhB2s+C06Qc+MaU5vo5VCpSnGAwiIVSMaambh9mSQTwsUdup3cvSO/IKK3OIMBiSReMXzSmD010pJ0ZmGzqGoH5mIuKusmaj5mYesHZ6lYfwcvvffDepmJgxAchlTD8iEPEDg0SGIfAogYeXwIDAQAB
    application:
      type: BACKEND_GATEWAY
      id: backend-gateway
    cookie:
      domain: ".example.com"
    domain:
      keycloak:
        issuerUri: https://aipub-keycloak.example.com/realms/aipub
    web:
      k8sProxy:
        k8sUri: https://10.96.0.1
      security:
        allowedOrigins_0: https://aipub.example.com
        allowedOrigin: https://aipub.example.com
        basicAuth:
          user:
            username: "testuser"
            password: "asdasdasd"
            role: "aipub-admin"
  logging:
    level:
      orgSpringframeworkWeb: info
